### ISSUE TITLE
localization.tw.lua

### ISSUE THREAD

**Issue by Se7enMuting** [DeadlyBossMods/DBM-Classic#101]
1.13.37
\DBM-BWL\localization.tw.lua
......
L:SetGeneralLocalization{
	name	= "勒西雷爾"
}
......
	VulnEmote	= "克洛瑪古斯因皮膚閃著微光而驚訝退縮。"
......
	YellP1		= "讓賽事開始吧！",
	YellP2		= "幹得好，手下們。凡人的勇氣開始消退了！現在，我們就來看看他們怎麼面對黑石之王的力量吧！",
	YellP3		= "不可能！來吧，我的僕人！再次為你們的主人服務！",
	YellShaman	= "薩滿，讓我看看你圖騰到底是什麼用處的！",
	YellPaladin	= "聖騎士……聽說你有無數條命。讓我看看到底是怎麼樣的吧。",
	YellDruid	= "德魯伊和你們愚蠢的變形。讓我們看看什麼會發生吧！",
	YellPriest	= "牧師！如果你要繼續這麼治療的話，那我們來玩點有趣的東西！",
	YellWarrior	= "戰士，我知道你應該比較抗打！讓我們來見識一下吧！",
	YellRogue	= "盜賊？不要躲了，面對我吧！",
	YellWarlock	= "術士，不要隨便去玩那些你不理解的法術。看看會發生什麼吧？",
	YellHunter	= "獵人和你那討厭的豌豆射擊！",
	YellMage	= "還有法師？你應該小心使用你的魔法……"
......
\DBM-Onyxia\localization.tw.lua
	Breath = "%s深深地吸了一口氣...",
	YellPull = "真是幸運。通常我為了覓食就必須離開窩。",
	YellP2 	= "這毫無意義的行動讓我很厭煩。我會從上空把你們都燒成灰！",
	YellP3 	= "看起來需要再給你一次教訓，凡人！"

**Comment by Se7enMuting** [comment]
[DBM-1.13.37-classic.zip](https://github.com/DeadlyBossMods/DBM-Classic/files/4248804/DBM-1.13.37-classic.zip)

**Comment by Se7enMuting** [comment]
BWL 3王的名字，7王的表情。
BWL 8王：YellP2，YellP3，YellShaman，這三段個別字和實際繁體客戶端有出入（注意”麼“字），下面的沒看出問題，反正我把客戶端裏直接複製下來的貼出來了。

Onyxia：
有時候吐息沒有提示，我看了下實際繁體客戶端的表情結尾是三個點。如果是包含檢測，是否可以把標點去掉？
YellP2，YellP3中結尾的“！”應該要是中文符號。

**Comment by Mini-Dragon** [comment]
fixed. 已修复

**Comment by Se7enMuting** [comment]
薩滿那句裏面的”麼“字
Onyxia吐息結尾是3個點

**Comment by Se7enMuting** [comment]
還有兩句：
	Phase2Emote	= "奈法利安的部隊在寶珠的控制力消失之前逃走。",
	Event	= "太遲了，朋友！奈法利斯的腐化掌控了我…我已經無法…控制自己了。"

**Comment by Mini-Dragon** [comment]
啊！没看到那个“麼”字。
经视频查证，Onyxia真的是三个点。

**Comment by Se7enMuting** [comment]
“麼”字你在 commit 359d173 已經修復。
下面是我在插件Elephant內複製出來的原始文字。
[台词.txt](https://github.com/DeadlyBossMods/DBM-Classic/files/4248912/default.txt)

**Comment by Mini-Dragon** [comment]
感谢，您看看还有啥问题没有~

**Comment by Se7enMuting** [comment]
YellP3	= "不可能！來吧
這個”來“不是繁體
YellP3開始用了空格，沒用tab，最好改成tab

**Comment by Mini-Dragon** [comment]
fixed. 已修复

**Comment by Se7enMuting** [comment]
又對照了下，MC的繁體臺詞也有點小問題
![批注 2020-03-05 142633](https://user-images.githubusercontent.com/889925/75954354-78cab780-5eee-11ea-812b-bae6da8f132e.png)
這句（"出現吧，我的奴僕! 保衛你們的主人!"）沒有問題，確實是英文格式的驚歎號，還有一個空格。下面那句要改成中文格式驚歎號。

[localization.tw.zip](https://github.com/DeadlyBossMods/DBM-Classic/files/4291304/localization.tw.zip)

**Comment by Mini-Dragon** [comment]
done
