### ISSUE TITLE
BWL: Razorgore Egg Counter

### ISSUE THREAD

**Issue by Road-block** [DeadlyBossMods/DBM-Classic#102]
**Is your feature request related to a problem? Please describe.**
An egg count on Razorgore would be nice as it's the only real measure of progress in the encounter.

**Describe the solution you'd like**
Message or bar (optional) would work nicely.

**Describe alternatives you've considered**

**Additional context**
I realize there is a stub for it already but output is disabled (other than debug) citing some issues with combatlog.

```
2/28 21:03:36.837  SPELL_CAST_SUCCESS,Creature-0-4457-469-3513-12435-0000595E35,"Razorgore the Untamed",0x1114,0x0,0000000000000000,nil,0x80000000,0x80000000,19873,"Destroy Egg",0x1,Creature-0-4457-469-3513-12435-0000595E35,0000000000000000,100,100,0,0,0,-1,0,0,0,-7611.15,-1018.99,0,3.9818,65
```
This is a sample combat log line for successful cast, there is also one for cast start.
What I'm thinking is that since there is a 3second cast time and a 7second cooldown on the ability "Destroy Egg", one could sync (to get around the range limitations) and use a 7 second frame (from success) for batching / filtering duplicate events.  
*First successful destroy egg that comes in starts a 7sec timer that discards all subsequent syncs in that time frame*

I guess I'm looking for a bit more feedback on what are the technical challenges with implementation 😃

**Comment by MysticalOS** [comment]
you can track the cast of destroy egg, but you can't detect whether or not it actually hits any eggs, or how many eggs

i saw logs that had it cast as many as 22 times or as few as 13 times, all being successful kills

the eggs themselves being hit/dying aren't in logs

if you had looked at mods code and saw preliminary code, that's why. I started work on it but scrapped the idea when it looked undoable

**Comment by Road-block** [comment]
Would getting the yells he does for each successful egg pop help?   
They are variable but he does one for each egg popped.  

"You'll pay for forcing me to do this!"  
"No - not another one! I'll have your heads for this atrocity!"  
"Fools! Those eggs are more precious than you know!"

Not sure if exhaustive, I hope I remember to run Transcriptor next time, see if I get something useful.  
I'll poke around the cascs see if there's some way to match the yells without relying on user provided localization?

In any case not an important feature by any stretch more in the "would be nice to have category" so any time you feel it's exhausted its usefulness just close ⚡️

**Comment by MysticalOS** [comment]
Does he yell for EVERY egg though? i always thought it was a bit random.

**Comment by Road-block** [comment]
The yells are random (from a set of preset phrases) but he does afaik yell for every egg. I'll run Transcriptor coming Friday if no one beats me to it to make sure.

**Comment by Road-block** [comment]
I couldn't resist going over our vod in the end.   
It helps that we are very efficient with egg popping but I'm 99.9% sure he does the yell for **every second** egg.

Every 20 to 21 seconds like clockwork (3+7 (silent) 3+7 (yells) all the way through)

So the yell essentially marks 2, 4, 6, 8, all the way to 30.

**Comment by MysticalOS** [comment]
That'd need to still be tested. often times yell just has an ICD, so it might just line up that way if no mistakes. but what happens if he breaks lose and runs around a while, and time between a single egg cast long enough to reach ICD so ye starts yelling at odds. That scenario needs to be tested to make sure he actually yells every 2, and not "he's coded to yell for all eggs, unless he yellled within x seconds"

**Comment by Road-block** [comment]
Absolutely, I'll run trasncriptor still, hopefully results are more conclusive.

**Comment by Road-block** [comment]
Yep confirmed, it's 15 yells exactly, I got transcriptor log this week and it was also a messier kill (training new orb controller) so there's no icd to account for the yells.
(I manually counted my earlier vod and it's also 15)
`He yells one of the 3 predefined phrases every other egg`

**Comment by Road-block** [comment]
https://gist.github.com/Road-block/c1dfab0f09ffba6a28492654b77ab10b

**Comment by Road-block** [comment]
Just saw a comment on another ticket that Classic is - by virtue of time - lower prio. 

Should I fork and make a pull request for this?
Would it require sync?

**Comment by Road-block** [comment]
So had a chance to see this at work.  
It's bugged. Firstly it skips over a few pairs directly to `Destroy Egg (24)` but ok maybe there's some message throttling.
Then it goes to 21 which for such simple code should be impossible (each detected yell is -2)
It keeps diverging for subsequent counts.  
I logged yells again and the previous analysis absolutely holds, 15yells for 30 eggs.  

I'll find a way to test the code outside a raid so I don't have to wait another week.  
Assuming I find why it's broken when the yells are correct I'd also prefer the count to be in the form of destroyed/total instead of eggsLeft so an announce like this
```lua
warnEggsLeft:Show(string.format("%d/%d",30-self.vb.eggsLeft,30))
```

**Comment by MysticalOS** [comment]
It looks like you never removed the original code

**Comment by Road-block** [comment]
I blame the twitch app if that's the case, supposed to remove previous version when it pulls down an update, but thanks for the hint, I'll check if I have ended up with some frankenpatch.

**Comment by MysticalOS** [comment]
No, you misunderstand, your pull request left the original egg counter from Destroy Egg casts in there. I never reviewed it because I assumed it tested already. I've now removed the original egg subtraction code so now it's using only yells

**Comment by Road-block** [comment]
Oh apologies for that I had the pull request tagged [WIP] exactly because it was untested 😄

**Comment by Road-block** [comment]
Tested the announce format change locally, looks nice.
![image](https://user-images.githubusercontent.com/109839/77217511-d33d5800-6b2b-11ea-9e28-1560c360000a.png)
```lua
warnEggsLeft:Show(string.format("%d/%d",30-self.vb.eggsLeft,30))
```
It's too trivial a change to make another pull request right?

**Comment by MysticalOS** [comment]
I added it. I'll leave this issue open until proper testing can be done with alpha. if it all tests in order I'll close issue.

**Comment by Road-block** [comment]
Looks ok for the most part.  
2 eggs off at the end and I didn't run Transcriptor 🤕   
[Razorgore Clip](https://www.twitch.tv/videos/577014053)

**Comment by MysticalOS** [comment]
Code wise, if your theory is sound it should be flawless.

i still suspect there is a yell throttle mechanic and if you manage to do eggs super fast (or super slow), the yell might happen at 1 egg, or 3, or just something other than 2 sometimes.

**Comment by Road-block** [comment]
I'll keep transcriptor on every reset going forward, but I've seen nothing to indicate anything different than 15 yells.  
At least for P1 between 5:30 to 6:10 or so. In any case it's much better than previously.

**Comment by Road-block** [comment]
Ok.. now I have 2 logs with exactly 15 yells and 1 log with 16 (plus the one I didn't run transcriptor with but counter also went 32/30, assuming that was 16 as well)

I need more logs with timestamps to see if I can make sense of this

[2020-04-03](https://gist.github.com/Road-block/c1dfab0f09ffba6a28492654b77ab10b/raw/699a7b1d52e22a6e6746ac9a9f6df5fede0a2af9/transcriptor.lua)

**Comment by MysticalOS** [comment]
New method pushed to new alpha, that should be more acceptable with combat log range increase, it needs testing.

**Comment by Road-block** [comment]
No egg count at all with recent alphas. Is it supposed to work for players other than the one controlling Razorgore?  
[Clip](https://www.twitch.tv/videos/662604239)

**Comment by MysticalOS** [comment]
Pushed a possible fix for it, you'll have to try it next time

**Comment by Road-block** [comment]
> 
> 
> Pushed a possible fix for it, you'll have to try it next time

Far as I can tell it works properly now 👍

**Comment by MysticalOS** [comment]
Good accurate counts?

**Comment by Road-block** [comment]
> 
> 
> Good accurate counts?

Count was exact P2 started at 30/30 and announcements were coming in single increments so yeah I'd say it's working pretty well.
