### ISSUE TITLE
Vulnerability checks cause spam and fps drops

### ISSUE THREAD

**Issue by nwardoh** [DeadlyBossMods/DBM-Classic#108]
Lag in BWL is unplayable with the new version. I am positive it is this addon.

**Comment by haleykoike** [comment]
There's a much more reliable way for checking vulnerabilities if Detect Magic is cast on the mob. The ID of the Elemental Shield spell aura on the mob can then be used to determine the vulnerability.

- 22277 - Fire
- 22278 - Frost
- 22279 - Shadow
- 22280 - Nature
- 22281 - Arcane

Here are a couple WeakAuras that do the Elemental Shield ID check for reference:
https://wago.io/cSKJYPLQR
https://wago.io/kf9gRHYdf

Performance and spam could be improved by doing a check based on the Elemental Shield aura first, and then falling back to the spell damage check only if Detect Magic / Elemental Shield aren't found on the target mob.

**Comment by MysticalOS** [comment]
it does check that first and once it finds vulnerability it unregisters events

**Comment by MysticalOS** [comment]
with no further reports, and a couple reports of it working fine, gonna assume it's fully resolved and works well with no performance issues after I redid how it worked from the PR. Closing
