### ISSUE TITLE
[Feature request] Additional tranquilize prompt after Frenzy call

### ISSUE THREAD

**Issue by lantisnt** [DeadlyBossMods/DBM-Classic#114]
For Tranquiliziation (Frenzy) Intensive fights sometimes Frenzies are missed because Hunter doesn't tranq in proper time. 

I would like to have an additional option that would add second alert to Hunters only (that would have Tranqilizing shot icon and coloring and would state "Tranquilize" etc).
This option should have configurable time delay - relative to Frenzy alert.

Intention of this is for hunters to know that after some time the enemy is still in Frenzy and shouldn't be. 

From my observations around 2s - 2.5s is time when the tranq should be done already, thus 2s value could be the default setting.

This request is intended for Classic, as BWL tranq rotation can be hard in BWL.

**Comment by MysticalOS** [comment]
This is handled fine by the buff timer. it shows enrage icon and spell and duration fo enrage, it auto hides timer when successfully removed. I did fix an issue where this behavior wasn't consistent between Flamegor and Chromaggus in above commit.
