### ISSUE TITLE
[classic] Please make Burning Adrenaline notification if "on you" much more noticeable.

### ISSUE THREAD

**Issue by pmb123** [DeadlyBossMods/DBM-Classic#124]
The personal warning, since you could potentially wipe the whole raid, should be more intrusive, like raid warning large or something like that.

**Comment by MysticalOS** [comment]
I'm going to change default sound, but just an FYI, you can change any special warning to ANY sound you want. it was already very noticable warning, in fact it gets two warnings, one when you get it and one 5 seconds before it's about to expire to run out. It seems to me that you might want to consider changing default sounds around a bit if you somehow manage to space this out. https://github.com/DeadlyBossMods/DeadlyBossMods/wiki/%5BGuide%5D-Special-Warning-Sound-Config

**Comment by pmb123** [comment]
thanks.  is there some sort of visual warning you can add too?  like for Hakkar or deep breath?

**Comment by MysticalOS** [comment]
it LITERALLY has one. it has TWO of them

**Comment by MysticalOS** [comment]
Ok, Improved fixes further for it in https://github.com/DeadlyBossMods/DBM-Classic/commit/9f5d23171dbc9bf9e0ab6acb300223da70762d7b and https://github.com/DeadlyBossMods/DBM-Classic/commit/856b7378b3ec6384ad10070d49651e5c66336e5e

This shouldn't be a problem anymore.

**Comment by pmb123** [comment]
yea, its something that I've gotten a few times and ive NEVER noticed it, but my fellow raid members let me know I have it...  where as I always noticed deep breath.  seemed to me that burning adrenaline was an outlier.
