### ISSUE TITLE
Unknown spell triggered LUA error

### ISSUE THREAD

**Issue by wallrik** [DeadlyBossMods/DBM-Classic#13]
**Describe the bug**
At the end of Stratholme living, when Balnazzar died, a spellId 66290 triggered and caused a lua error with DBM. I cannot find that spell on Wowhead so I assume it's something that's supposed to be hidden from the client normally.

**Do you have an error log of what happened?**
```
Message: Interface\AddOns\DBM-Core\DBM-Core.lua:852: table index is nil
Time: Mon Sep 23 23:24:18 2019
Count: 1
Stack: Interface\AddOns\DBM-Core\DBM-Core.lua:852: table index is nil
Interface\AddOns\DBM-Core\DBM-Core.lua:852: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:848>
Interface\AddOns\DBM-Core\DBM-Core.lua:891: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:884>
Interface\AddOns\DBM-Core\DBM-Core.lua:1009: in function `UnregisterInCombatEvents'
Interface\AddOns\DBM-Core\DBM-Core.lua:5727: in function `EndCombat'
Interface\AddOns\DBM-Core\DBM-Core.lua:5408: in function `func'
Interface\AddOns\DBM-Core\DBM-Core.lua:1707: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:1698>

Locals: event = "SPELL_AURA_APPLIED"
spellId = 66290
spellName = nil
refs = 0
(*temporary) = <table> {
}
(*temporary) = "table index is nil"
registeredSpellIds = <table> {
 SPELL_AURA_APPLIED = <table> {
 }
 SPELL_CAST_SUCCESS = <table> {
 }
}
```

**To Reproduce**
I have no idea if it can be reproduced, but maybe something that trigged that made me able to pick up the Head of Balnazzar made it trigger that spell, because other times I've killed him I haven't seen this. I must have completed some pre-quest now that I didn't have before.

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
The only other addon I use is Questie.

**Which version of DeadlyBossMods are you using?**
1.13.11

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
This was already fixed in alpha version. Thanks for report
