### ISSUE TITLE
world buffs timer / alert

### ISSUE THREAD

**Issue by knasen88** [DeadlyBossMods/DBM-Classic#14]
**Is your feature request related to a problem? Please describe.**
Well its missing i suppose

**Describe the solution you'd like**
whenever world buff shouts like onyxia and WCB buff happens, display a timer counting down and also a soundfile preferably some nuclear launch detected alarm.

**Describe alternatives you've considered**
The old 1.12 version of bigwigs modified to private servers had this feature

**Additional context**
only load while in orgrimmar / Stormwind / ZG island - booty bay?

**Comment by MysticalOS** [comment]
This isn't being ignored, it's just something that won't be looked at for quite a while do to the retail wow work load right now, and fact that while layering is on in classic it's an utter pain in ass to track world buffs right now.

**Comment by knasen88** [comment]
its not about tracking CD, its about when it goes off. The CD is easily observed by watching when theres a head up or not.
