### ISSUE TITLE
{ unknown buff } ( Ony / Nef / Hexxar )

### ISSUE THREAD

**Issue by 001345149** [DeadlyBossMods/DBM-Classic#184]
The buff sent is unknown.  **Bug within last update

**Comment by MysticalOS** [comment]
I don't understand the error, I need more context

**Comment by nanjuekaien1** [comment]
@MysticalOS  What he meant was that when the World buff was obtained, the channel notification showed: unknown buff has started on your realm for %s faction (Sent by %s).

**Comment by woopydalan** [comment]
I noticed this same error that @nanjuekaien1 is describing
