### ISSUE TITLE
Lib errors, non-existant Lib folder

### ISSUE THREAD

**Issue by Norjak** [DeadlyBossMods/DBM-Classic#185]
I noticed when I have Script errors turned on ("/console scripterrors 1"), I am seeing the following errors. It appears to be looking for a folder that does not exist.

Error loading Interface\AddOns\DBM-Core\Libs\LibStub\LibStub.lua

Couldn't open Interface\AddOns\DBM-Core\Libs\CallbackHandler-1.0-7\CallbackHandler-1.0.xml

Couldn't open Interface\AddOns\DBM-Core\Libs\LibChatAnims\LibChatAnims.xml

Couldn't open Interface\AddOns\DBM-Core\Libs\LibSharedMedia-3.0-8020003\lib.xml

Couldn't open Interface\AddOns\DBM-Core\Libs\LibLatency\LibLatency.xml

Couldn't open Interface\AddOns\DBM-Core\Libs\LibDurability\LibDurability.xml

Error loading Interface\AddOns\DBM-Core\Libs\LibDataBroker-1.1\LibDataBroker-1.1-4.lua

Couldn't open Interface\AddOns\DBM-Core\Libs\LibDBIcon-1.0-43\lib.xml

Couldn't open Interface\AddOns\DBM-Core\Libs\LibThreatClassic2\lib.xml

**Comment by QartemisT** [comment]
Did you by any chance install the "no libs" version of DBM-Classic?

**Comment by Norjak** [comment]
I downloaded DBM directly from Github, which does not have the related Libs folder under DBM-Core. I found that the version on Curseforge does contain this folder, when I copied this version into my local Addons the errors no longer occur.

**Comment by MysticalOS** [comment]
even downloaded from github it's fine. IF downloaded from RELEASES here https://github.com/DeadlyBossMods/DBM-Classic/releases

it sounds like you clicked "download or clone" on source code view. When downloading/checking out code libs aren't included. That download method should only be done by a developer that knows how to fetch externals.
