### ISSUE TITLE
overlapping

### ISSUE THREAD

**Issue by nanjuekaien1** [DeadlyBossMods/DBM-Classic#233]
@ QartemisT 
![位置](https://user-images.githubusercontent.com/2303601/84569152-e83a2800-adb6-11ea-9068-5e1c38aa15b5.jpg)
Flash screen and  Set default sound  overlapping

**Comment by QartemisT** [comment]
Are you running thr latest release that we put out yesterday?

**Comment by nanjuekaien1** [comment]
Yes @QartemisT

**Comment by nanjuekaien1** [comment]
@QartemisT   1.13.50alpha  The spacing between the Bar Behavior Options in the  Timers is increased, and the Role Filter Options in the Spoken Alerts are both.
![错误](https://user-images.githubusercontent.com/2303601/84613011-d363ae80-aef4-11ea-915a-a7fb16637855.jpg)
![错误2](https://user-images.githubusercontent.com/2303601/84613022-d5c60880-aef4-11ea-8cc6-3f758bf542c1.jpg)
![错误3](https://user-images.githubusercontent.com/2303601/84613026-d8286280-aef4-11ea-9ea6-a41e27628d47.jpg)
![错误4](https://user-images.githubusercontent.com/2303601/84613030-d9f22600-aef4-11ea-993b-6f999beba049.jpg)
![错误5](https://user-images.githubusercontent.com/2303601/84613032-dbbbe980-aef4-11ea-90fe-179bd91bed9f.jpg)

**Comment by MysticalOS** [comment]
That almost looks like the classic set point hackwas lost? Let me double check that

**Comment by nanjuekaien1** [comment]
:(

**Comment by MysticalOS** [comment]
Ok, Fixed the space between checkboxes issues. Gonna check overlaps too, probably restore fixed width to those drop downs like they used to have.
