### ISSUE TITLE
Remove that annoying squeaky english men sounds from DBM Onyxia!!!

### ISSUE THREAD

**Issue by Kulturnilpferd** [DeadlyBossMods/DBM-Classic#28]
**Describe the bug**
I hear every time i kill onyxia some english squeaky mofo who wants to tell me how i should kill onyxia. There is no option to disable it, i don't care about this shit its not funny and really really sucks!

**Comment by Kulturnilpferd** [comment]
Beside that is the sound quality sucks also, even a santa hohoho whould be better as this fucking shit!!!

**Comment by MysticalOS** [comment]
just turn it off in onyxia mod options, there has always been a disable for that.

the quality is part of the meme, if you don't get the meme then it'll go over your head.

**Comment by Kulturnilpferd** [comment]
Its just bullshit i don't care about stupid memes in my gameplay

**Comment by Kulturnilpferd** [comment]
Do some christmas special instead...
