### ISSUE TITLE
DBM GUI: Scrollbar issues with non-default height

### ISSUE THREAD

**Issue by wallrik** [DeadlyBossMods/DBM-Classic#317]
If you set the height to around 700 you get two weird errors. I dug around a little bit, but won't solve anything tonight.
### Lua error
1. Under Options > General Options, set GUI window height to 700
2. Select the section **Announcements**
Lua error appears because max is a negative value:
```
Interface\AddOns\DBM-GUI\modules\MainFramePrototype.lua:181: Usage: DBM_GUI_OptionsFramePanelContainerFOVScrollBar:SetMinMaxValues(min, max)
[C]: in function `SetMinMaxValues'
Interface\AddOns\DBM-GUI\modules\MainFramePrototype.lua:181: in function `DisplayFrame'
Interface\AddOns\DBM-GUI\modules\MainFrame.lua:171: in function <Interface\AddOns\DBM-GUI\modules\MainFrame.lua:167>

Locals:
(*temporary) = DBM_GUI_OptionsFramePanelContainerFOVScrollBar {
 0 = <userdata>
 ThumbTexture = DBM_GUI_OptionsFramePanelContainerFOVScrollBarThumbTexture { }
 ScrollUpButton = DBM_GUI_OptionsFramePanelContainerFOVScrollBarScrollUpButton { }
 ScrollDownButton = DBM_GUI_OptionsFramePanelContainerFOVScrollBarScrollDownButton { }
}
(*temporary) = 0
(*temporary) = -4.000015
```
### Weird frame height
1. Under Options > General Options, set GUI window height to 700
2. Select the section **Extra Features**
No scrollbar appears and thus cutting off options at the bottom
3. Select the section **Extra Features** again
The height is reported differently and scrollbars appear again
4. Reload UI and repeats steps 2 and 3

**Comment by QartemisT** [comment]
Okay, I'm thinking that there's a SPECIFIC fine number, where the actual height is the exact same as the predicted height.

Time to math :D

**Comment by wallrik** [comment]
If I comment out the `+20` here, it's fine:
https://github.com/DeadlyBossMods/DBM-Classic/blob/47ef28c0868b72280486ff131b89ebdb5ea3b675/DBM-GUI/modules/MainFramePrototype.lua#L82
Because this logic doesn't work then:
https://github.com/DeadlyBossMods/DBM-Classic/blob/47ef28c0868b72280486ff131b89ebdb5ea3b675/DBM-GUI/modules/MainFramePrototype.lua#L95-L98
But I haven't spent enough time with it to understand why the 20 is added from the start.

**Comment by QartemisT** [comment]
Yeh the math there is very precise :P I put over a fix on retail side, but I really do need to go around and rewrite most of that code :P Its terrible, and terrible :D
