### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by Slivo-fr** [DeadlyBossMods/DBM-Classic#326]
**Describe the bug**
I'm getting a lua error when I enter BRD

**Do you have an error log of what happened?**
```
19x DBM-WorldEvents\Holidays\Brew.lua:20: attempt to index global 'C_Calendar' (a nil value)
DBM-WorldEvents\Holidays\Brew.lua:20: in function `CheckEventActive'
DBM-WorldEvents\Holidays\Brew.lua:32: in main chunk
[C]: in function `LoadAddOn'
DBM-Core\DBM-Core-1.13.47.lua:3963: in function `LoadMod'
DBM-Core\DBM-Core-1.13.47.lua:3924: in function `LoadModsOnDemand'
DBM-Core\DBM-Core-1.13.47.lua:3877: in function `func'
DBM-Core\DBM-Core-1.13.47.lua:1803: in function <DBM-Core\DBM-Core.lua:1794>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'C_Calendar' (a nil value)"
setActive = false

```

**To Reproduce**
1. Enter BRD

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of DeadlyBossMods are you using?**
1.13.52

**Was it working in a previous version? If yes, which was the last good one?**
No idea

**Comment by MysticalOS** [comment]
World events should not be installed in classic, that's a retail only mod, delete it entirely and any other addons you installed over from retail that don't have a classic version available.

the only addons that should be installed in classic are ones included in classic package and the optional mods PVP or spelltimers, or any of media packs like countdown voices or voice packs or sound events.

**Comment by Slivo-fr** [comment]
Sorry about it, might be a curse fail then ! Thanks for your answer :)
