### ISSUE TITLE
AQ additions

### ISSUE THREAD

**Issue by venuatu** [DeadlyBossMods/DBM-Classic#332]
# AQ20
1. rajaxx
    - [ ]  low health warning for the aura guy
2. flesh hunter
    - [ ] consume yell https://classic.wowhead.com/spell=25371/consume
3. anubisath guardian 
    -   [x] plague say (similar to corrupted blood)
    -   [x] shadow and frost reflect https://www.wowhead.com/spell=19595/shadow-and-frost-reflect
    -   [x] Fire and Arcane Reflect https://www.wowhead.com/spell=13022/fire-and-arcane-reflect
    -   [x] explode
    -   [x] meteor (excluded due to no cast and false positives)
4. hivezara sandstalker (people generally don't go this way)
    -   [ ] burrow warning

# AQ40
1. anubisath sentinel
    -   [x] shadow and frost reflect https://www.wowhead.com/spell=19595/shadow-and-frost-reflect
    -   [x] Fire and Arcane Reflect https://www.wowhead.com/spell=13022/fire-and-arcane-reflect
    -   [x] Shadow Storm - player should move inside range
2. anubisath defender
     -   [x] plague say (similar to corrupted blood)
     -   [x] explode
     -   [x] meteor (excluded due to no cast and false positives)
3. fankriss
    -   [x] entangle yell
4. viscidius
    -   [x] toxin move warning
5. bugs
    -   [x] toxin move warning (vem?)
6. Princess Huhuran
    -   [x] Add range frame for Princess Huhuran, Noxious Poison
7. C'thun
    -   [x] Maybe re-add timers for tentacles and such when CLASSIC logs can be verified with accurate information about spawns and phase change affects on spawns. (NOTE: don't use retail, encounter recieved several changes to speed up soloing the raid. Those behaviors are not normal/expected in classic.
    -   [x] Add infoframe showing who's in stomach, and stomach health percents, if possible. Depends if this information is available to players outside of phase.
8. Qiraji Mindslayer
    -   [x] cause insanity
9. Buro
    -   [x] review timers again for initial cast. They were wildly inconsistent on retail and disabled years ago, but maybe in classic they aren't? (probably wishful thinking)

**Comment by wallrik** [comment]
User suggestion on Discord: Add range frame for Princess Huhuran, [Noxious Poison](https://classic.wowhead.com/spell=26053/noxious-poison)

**Comment by Cyanokaze** [comment]
> ~User suggestion on Discord: Add range frame for Princess Huhuran, [Noxious Poison](https://classic.wowhead.com/spell=26053/noxious-poison)~
> 
> Never mind, already added in [71f621e](https://github.com/DeadlyBossMods/DBM-Classic/commit/71f621e468d1d978d58b5982b3e801ede539a7a7) 😊

18 yards? or 10 yards?

**Comment by venuatu** [comment]
@Cyanokaze from that commit it's on 18 yards
`mod:AddRangeFrameOption("18", nil, "-Melee")` and `DBM.RangeCheck:Show(18)`

**Comment by Cyanokaze** [comment]
> @Cyanokaze from that commit it's on 18 yards
> `mod:AddRangeFrameOption("18", nil, "-Melee")` and `DBM.RangeCheck:Show(18)`

But in our raid, if I keep 10 yards from other player, will never got Huhulan silent poison from him.
It's a question.

**Comment by MysticalOS** [comment]
The actual spell data says 15 yards, that's why mod is 18 (15 isn't a suppored range sadly)
