### ISSUE TITLE
ZG & AQ20 ru update

### ISSUE THREAD

**Issue by JekaLich** [DeadlyBossMods/DBM-Classic#335]
DBM-ZG\localization.ru.lua

-------------------
--  Thekal  --
-------------------

L:SetMiscLocalization({
	PriestDied	= "%s умирает.",
	YellPhase2	= "Ширвалла, наполни меня своим ГНЕВОМ!",
	YellKill	= "Хаккар больше не властен надо мной! Наконец-то я обрел покой!"
})

DBM-AQ20\localization.ru.lua

------------
-- Rajaxx --
------------

L:SetMiscLocalization{
	Wave1		= "Они пришли. Постарайся не дать себя убить, девушка.",
	Wave3		= "Час возмездия близок! Да охватит мрак сердца наших врагов!",
	Wave4		= "Мы не будем больше ждать за закрытыми дверьми и каменными стенами! Мы не будем больше отказываться от возмездия! Даже драконы содрогнутся перед нашим гневом!",
	Wave5		= "Пусть наши враги трепещут! Смерть им!",
	Wave6		= "Олений Шлем будет скулить и молить о пощаде, в точности как его сопливый сынок! Тысячелетняя несправедливость сегодня закончится!",
	Wave7		= "Фэндрал! Твой час пробил! Иди же, прячься в изумрудном сне и молись, чтобы мы до тебя не добрались!",
	Wave8		= "Impudent fool! I will kill you myself!" // I can't find russian text for this
}

**Comment by anon1231823** [comment]
Hi @JekaLich 

Can you get the phrase from Bloodlord Mandokir for russian

GazeYell	= "I'm watching you"

**Comment by JekaLich** [comment]
@anon1231823 
GazeYell = "Я за тобой слежу!"

**Comment by anon1231823** [comment]
@JekaLich 

Open BWL localization.en.lua and compare with localization.ru.lua

Please add any missing items such as

`-----------------------
--  Vulnerabilities  --
-----------------------
-- Chromaggus, Death Talon Overseer and Death Talon Wyrmguard
L = DBM:GetModLocalization("TalonGuards")

L:SetGeneralLocalization{
	name = "Talon Guards"
}
L:SetWarningLocalization{
	WarnVulnerable		= "%s Vulnerability"
}
L:SetOptionLocalization{
	WarnVulnerable		= "Show warning for spell vulnerabilities"
}
L:SetMiscLocalization{
	Fire		= "Fire",
	Nature		= "Nature",
	Frost		= "Frost",
	Shadow		= "Shadow",
	Arcane		= "Arcane",
	Holy		= "Holy"
}`

**Comment by JekaLich** [comment]
-----------------------
--  Vulnerabilities  --
-----------------------
-- Chromaggus, Death Talon Overseer and Death Talon Wyrmguard
L = DBM:GetModLocalization("TalonGuards")

L:SetGeneralLocalization{
	name = "Стражи Когтя Смерти"
}
L:SetWarningLocalization{
	WarnVulnerable		= "Уязвимость к %s"
}
L:SetOptionLocalization{
	WarnVulnerable		= "Показывать предупреждение об уязвимости к заклинаниям"
}
L:SetMiscLocalization{
	Fire		= "Огню",
	Nature		= "силам Природы",
	Frost		= "магии Льда",
	Shadow		= "Темной магии",
	Arcane		= "Тайной магии",
	Holy		= "Светлой магии"
}

**Comment by anon1231823** [comment]
@JekaLich 

Please open 
https://github.com/DeadlyBossMods/DBM-Classic/blob/master/DBM-BWL/localization.en.lua

https://github.com/DeadlyBossMods/DBM-Classic/blob/master/DBM-BWL/localization.ru.lua

Look for all missing stuff in russian and translate it. There is missing stuff from Chromaggus as well

**Comment by anon1231823** [comment]
@JekaLich 
When you are translating boss phrases, are you using the chatlog, or are you just translating it from your head? It has to match exact name in-game to work. I'm just letting you know in case you didn't use the chatlog but are translating yourself.

**Comment by JekaLich** [comment]
I'm using chat log only

**Comment by anon1231823** [comment]
@JekaLich Thanks, please go through the English and Russian files and compare. Look through Azeroth, MC, Dungeons, BWL, ZG, AQ and make sure there are no missing strings in russian. When new stuff is added, it is not put in the other localization files. You have to look in the english one and make sure it has the same as russian.

**Comment by anon1231823** [comment]
@JekaLich You can edit and open the russian file and translate it yourself and make a pull request. No need to create an issue from it.

**Comment by JekaLich** [comment]
@anon1231823 Okay, got it
