### ISSUE TITLE
Add last know Onyxia head turn-in time

### ISSUE THREAD

**Issue by Jakobud** [DeadlyBossMods/DBM-Classic#35]
**Is your feature request related to a problem? Please describe.**
Whenever someone turns in the Onyxia head quest, all of Orgrimmar gets the buff from it. People can turn in the head quest as often as they want, however the zone-wide buff will not always go out. It appears to be a 6 hour cooldown (this needs to be verified). So now people are always asking in general and trade chat "When is the next Ony head buff" etc. There is no reliable way to know unless someone was there and remembered exactly when it last happened. What if there was an addon that told when the last head buff was dropped?

**Describe the solution you'd like**
DBM already has a built-in guild-wide timer to show when an Onyxia head buff is about to happen. What would be awesome is if DBM also was recording the time when the buff is applied. And then DBM would be able to report this to other guild members and party members and raid members. So that at any time, someone anyone using DBM could look at the last known time/date when an Ony head buff was dropped. Since DBM doesn't really have a UI to speak of I think in the Interface Options panel in the Onyxia section would be the best place to show this information. Just show something like "Last known Onyxia head buff: 13:45".

This obviously isn't fool-proof. If no guild member is online or in Org when a head drops then there is no way it will get recorded and then becomes unreliable. But if this recorded time was synced between not just guild members but between party and raid members whenever someone joins a group, that update could then sync to other members in the players guild, etc. An accurate time could get spread around very quickly and it would be fairly reliable.

I'm not sure if DBM is the proper addon to handle this. But it's as good as any and it's very widely used so that would help the value be properly spread between players in guilds/parties/raids. And DBM already does the countdown thing anyways, so why not add this functionality as well?

Anyways, it would be pretty awesome. Keep up the great work!

**Comment by mattmartinez** [comment]
You turn the head into can be mind controlled and killed (which happens almost every day on my server). He respawns after 5 minutes and you can turn the head back in and the buff goes out again. So in the event you don't have a raider/party/guildy in the zone when a "reseted" raid buff goes out you'll mess up that timer too.

**Comment by MysticalOS** [comment]
Closing this. because of reset shanigans plus the total lack of time for extra classic features. Just going to decline doing anything more with this feature.

**Comment by Jakobud** [comment]
Nova World Buffs addon being used by everyone now. You guys missed the boat :-/

**Comment by MysticalOS** [comment]
It basically comes down to https://twitter.com/deadlybossmods/status/1260274480800292866

They might be taking over making raid mods too in near future if things don't change.
