### ISSUE TITLE
Add Additional Dungeon Support

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DBM-Classic#4]
**Add Warnings/Timers (Mods exist and have basic stats/combat detection):**
- [ ] Blackrock Depths
- [ ] Dire Maul
- [ ] Lower Blackrock Spire
- [ ] Upper Blackrock Spire
- [ ] Scholomance

**How to help?**
1. Share combat logs recorded with advanced combat logging and uploaded to WarcraftLogs or combatlog.txt shared with MysticalOS on Discord
2. Share transcriptor logs captured with Transcriptor in game.
Ideally both, because transcriptor logs will omit spellId, but combat logs will omit yells/emotes/etc.

**Comment by wallrik** [comment]
For future development - got some logs here from Scholo.
[WoWCombatLog-Scholo1.txt](https://github.com/DeadlyBossMods/DBM-Classic/files/3715051/WoWCombatLog-Scholo1.txt)
[WoWCombatLog-Scholo2.txt](https://github.com/DeadlyBossMods/DBM-Classic/files/3715052/WoWCombatLog-Scholo2.txt)
[WoWCombatLog-Scholo3.txt](https://github.com/DeadlyBossMods/DBM-Classic/files/3715053/WoWCombatLog-Scholo3.txt)

**Comment by MysticalOS** [comment]
No additional dungeon mods will be added
