### ISSUE TITLE
aq40 Anubisath

### ISSUE THREAD

**Issue by nanjuekaien1** [DeadlyBossMods/DBM-Classic#438]
@MysticalOS @QartemisT 
26558, -- Meteor
26555, -- Shadow Storm
26554, -- Thunderclap

I can’t open the wiki, can you help me verify these three skill IDs?
if you have time，
thanks

**Comment by MysticalOS** [comment]
https://classic.wowhead.com/spell=26555/meteor
https://classic.wowhead.com/spell=26555/shadow-storm
https://classic.wowhead.com/spell=26554/thunderclap

**Comment by MysticalOS** [comment]
You can do /dump GetSpellInfo(id)
in game as well with those and it'll dump out in current local

**Comment by nanjuekaien1** [comment]
@MysticalOS I just found that the DBM-AQ40 module does not have these three skills, and I am going to add it to other plug-in monitoring after verification.
Thank you for verifying it for me.

**Comment by MysticalOS** [comment]
If suggested additions add them to 
https://github.com/DeadlyBossMods/DBM-Classic/issues/332
