### ISSUE TITLE
Add a 'whose loot is it' feature for classic?

### ISSUE THREAD

**Issue by mspk7305** [DeadlyBossMods/DBM-Classic#44]
The one phrase you hear over and over in MC is 'LOOT THE DOG'. There is an addon specifically for that type of thing right now but its something everyone needs to have... But DBM is something everyone needs to have and mostly do have already. So could a loot rights feature be added?

Please!?!

**Comment by Gogo1951** [comment]
GogoLoot will have this feature in BC. (=
