### ISSUE TITLE
twitch launcher installed wrong version

### ISSUE THREAD

**Issue by desecfutz** [DeadlyBossMods/DBM-Classic#451]
the twitch launcher installed the retail version of DBM for classic... not sure whether this is a you issue or the them issue... just letting you know... <3

**Comment by QartemisT** [comment]
Same report as of over at; https://github.com/DeadlyBossMods/DeadlyBossMods/issues/292

CopyPasta:
`Twitch client appears to have broken earlier today, and gave several users out of date addons/incorrect ones.

this goes back to what I always tell users. Make sure twitch client isn't messing it up. look at game version, look at file version, if something looks off (such as version being 8.3.x but it should be for classic). It seems resolved for now but yes always keep an eye on twitch client`
