### ISSUE TITLE
Enhancement: Fury/Prot DW tank not recognized as tank

### ISSUE THREAD

**Issue by lantisnt** [DeadlyBossMods/DBM-Classic#461]
**Twitch client installed classic/retail version on retail/classic**
Classic

**Describe the bug**
Fury/Prot 0/31(32)/20(19) DW Tank build is not recognized as tank

**Which version of DeadlyBossMods are you using?**
1.13.56

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**
`DBM:SetCurrentSpecInfo()` requires special treatment for this case

**Comment by venuatu** [comment]
This kind of thing should just check for defensive stance, bear form or maybe righteous fury, before showing the warning/bars
The fury prot spec would help, but it seems like there is an off tank meta where they are full dps fury and just put on a shield and defensive stance

**Comment by MysticalOS** [comment]
That applies for conditions that check on event, but these are on load conditions. the mod option defaults and mod profiles. I suppose optionally the tank warnings across all mods can just be set to on by default in options, and then use the mod:IsTank() object in all executions. Something similar is done on live using the Role check code (which sadly blizz removed in classic or things would have been easier). That said, the common tank specs and stance can be checked in the IsTank() object and then at least a few mods changed.

I wouldn't really mess with the spec objects though. That can get ugly hacky. But I'd review a PR tht goes either route and if I'm happy with code I'll approve, it just can't be too ugly or burdensom and it has to be sure enough that it won't suddenly be telling fury DPS warriors to start taunting the boss or something.
