### ISSUE TITLE
BlueNightSky  进

### ISSUE THREAD

**Issue by nanjuekaien1** [DeadlyBossMods/DBM-Classic#482]
@BlueNightSky  台服的TAQ现在服务器物资都不够，大门还没开启，方便的时候，可以在正式服的端口帮忙核对下信息吗？我们提前做好准备帮助台服玩家加快副本进度。
aq20 ： 
拉賈克斯將軍
Wave12		= "它們來了。盡量別被它們幹掉，新兵。", 	
Wave12Alt	= "拉贾克斯，还记得我说过要杀光其它虫子之后再干掉你么？",
Wave3		= "我們懲罰的時刻就在眼前!讓黑暗支配敵人的內心吧!", 	
 Wave4		= "我們不需在被禁堵的門與石牆後等待了!我們的復仇將不再被否認!巨龍將在我們的憤怒之前顫抖!",
Wave5		= "恐懼是給敵人的!恐懼與死亡!",
Wave6		= "鹿盔將為了活命而啜泣、乞求，就像他的兒子一樣!一千年的不公將在今日結束!",
Wave7		= "范達爾!你的時候到了!躲進翡翠夢境祈禱我們永遠不會找到你吧!",	
Wave8		= "厚顏無恥的笨蛋!我要親手殺了你!"

AQ40：
維希度斯
	Slow	= "開始減速!",
	Freezing  = "凍住了",
	Frozen	= "變成冰凍的固體!",
	Phase4 	= "開始爆裂!",
	Phase5 	= "看來準備好毀滅了!",
	Phase6 	= "爆炸。"        --这里需要仔细下，我在国服收集的战斗日志内没发现，后期找了4个视频看也没发现。不知道是不是国服的翻译遗漏还是什么问题。
以上是需要核对首领喊话的
克蘇恩模块是需要核对下名字对不对。
克蘇恩
        WarnClawTentacle		= "利爪觸鬚",
	WarnGiantEyeTentacle	= "巨眼觸鬚",
	WarnGiantClawTentacle	= "巨鉤觸鬚",
        Stomach		= "克蘇恩的胃",
        FleshTent	   = "血肉觸鬚",

现谢了。

**Comment by anon1231823** [comment]
Wave12Alt	= "拉贾克斯，还记得我说过要杀光其它虫子之后再干掉你么？",

**Comment by BlueNightSky** [comment]
您的意思是我在正式服，然後進懷舊副本去看看這些訊息跟名字對不對是嗎？好的，有空的時候，很樂意幫忙，可能要等週末。

**Comment by nanjuekaien1** [comment]
嗯，不过维希度斯你了小心点啊，手下留情，不要打死
