### ISSUE TITLE
Review raids and fix bugs related to incorrect timers and events

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DBM-Classic#5]
All raids are supported, but a lot of the work was done on retail, then backported to classic. Every raid needs full review to ensure timers are accurate, and events/triggers fight use, are functional.

**Phase 1:**
- [x] Onyxia
- [x] Molten Core

**Phase 3:**
- [x] Blackwing Lair

**Phase 4:**
- [x] Zul'Gurub

**Phase 5:**
- [x] Aq20
- [x] Aq40

**Phase 6:**
- [x] Naxxramas

**How to help?**
1. Share combat logs recorded with advanced combat logging and uploaded to WarcraftLogs
2. Share transcriptor logs captured with Transcriptor in game (not currently functional in classic yet, but whenever it is).
Ideally both, because transcriptor logs will omit spellId, but combat logs will omit yells/emotes/etc.
3. Report bugs, make suggestions, etc. Note anything that doesn't work correctly or feels like it's missing, or something that does exist but probably shouldn't (maybe it's too spammy, etc).

**Comment by MysticalOS** [comment]
Nax Notes:

Thaddius:
Phase 2 detection didn't work, so tank timers kept looping and initial timers for phase 2 (berserk and first charge assignment) didn't work.
Also need to actually verify tank throw timer

Gluth:
Decimate timer didn't seem right, or if it was it didn't trigger correctly

Patchwerk:
Verify Berserk

Globulus:
Looked pretty good, but should add no filter target announce for debuff targets, currently mod only showed timer with filters enabled.

**Comment by amotosouoc** [comment]
Gothik waves are as follows:
{3, L.Trainee, next = 20},
	{3, L.Trainee, next = 20},
	{3, L.Trainee, next = 10},
  {2, L.Knight, next = 10},
	{3, L.Trainee, next = 15},
	{2, L.Knight, next = 5},
	{3, L.Trainee, next = 20},
	{2, L.Knight, 3, L.Trainee, next = 10},
	{1, L.Rider, next = 10},
	{3, L.Trainee, next = 5},
	{2, L.Knight, next = 15},
	{1, L.Rider, 3, L.Trainee, next = 10},
	{2, L.Knight, next = 10},
	{3, L.Trainee, next = 10},
	{1, L.Rider,  next = 5},
	{2, L.Knight, next = 5},
	{3, L.Trainee, next = 20},
	{1, L.Rider, 2, L.Knight, 3, L.Trainee},

With first wave spawning after 28s
https://www.twitch.tv/videos/771458467?t=1h4m49s

**Comment by momo2366** [comment]
Thaddius‘ berserk timer is not correct.

It should be 305s.

https://classic.warcraftlogs.com/reports/Y1xJ9y8aLQNBRDzh#fight=104&hostility=1&type=auras&ability=27680

P2 start at 00:02:02.449

Boss gains berserk at 00:07:09.119

**Comment by HOYS** [comment]
https://classic.warcraftlogs.com/reports/kmWp1FhGDQYzNgn7#fight=9&type=auras&hostility=1&source=128&view=events

Berserk observed here at ~300 seconds
