### ISSUE TITLE
 Special warnings for low levels

### ISSUE THREAD

**Issue by Melf1ce** [DeadlyBossMods/DBM-Classic#603]
**Is your feature request related to a problem? Please describe.**
- Во время очередного ворлд бафа, если персонаж находящий в игре не хай лвл(60).
Например я обычно на персонаже 35го уровня, ворлд бафы (Ониксия и т.д.) не запускают таймер на этих персонажах что весьма прискорбно.

**Describe the solution you'd like**
-Запускать таймер на ожидающегося ворлд бафа на персонажах низкого уровня, для более удобного сбора таковых.

**Describe alternatives you've considered**
-Альтернатива есть на 60уровне, здесь же она попросту отсутствует.

**Additional context**
-https://ibb.co/PhdF3Gv

**Comment by MysticalOS** [comment]
There is no level restriction on timer/alert activation. If you get a sync (or see yell yourself) You will get timer. Now I do not know for certain if maybe it's a translation issue with the trigger for Russian text. I'll ask someone to look at that.
