### ISSUE TITLE
Bug Report from Client. Classic

### ISSUE THREAD

**Issue by Jeraax** [DeadlyBossMods/DBM-Classic#610]
Date: 2020-10-20 11:22:16
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\DBM-Core\DBM-Core.lua line 4805:
   CreateFrame(): Couldn't find inherited node "BackdropTemplate"
Debug:
   [C]: CreateFrame()
   DBM-Core\DBM-Core.lua:4805: in main chunk
Locals:
(*temporary) = "Frame"
(*temporary) = "DBMPopupLockout"
(*temporary) = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
}
(*temporary) = "BackdropTemplate"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.4.0
  Atlas, vv1.47.03.11304.00
  AtlasClassicWoW, vv1.47.02.11304.00
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.0.3
  Bartender4, v4.10.5
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BetterVendorPrice, vv1.13.07
  CharacterStatsClassic, v3.6.5
  Clique, vv1.0.3-classic
  DBMCore, v9.0.1
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=3ea)

Date: 2020-10-20 11:22:16
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\DBM-Core\DBM-Flash.lua line 15:
   CreateFrame(): Couldn't find inherited node "BackdropTemplate"
Debug:
   [C]: CreateFrame()
   DBM-Core\DBM-Flash.lua:15: in main chunk
Locals:
(*temporary) = "Frame"
(*temporary) = "DBMFlash"
(*temporary) = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
}
(*temporary) = "BackdropTemplate"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.4.0
  Atlas, vv1.47.03.11304.00
  AtlasClassicWoW, vv1.47.02.11304.00
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.0.3
  Bartender4, v4.10.5
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BetterVendorPrice, vv1.13.07
  CharacterStatsClassic, v3.6.5
  Clique, vv1.0.3-classic
  DBMCore, v9.0.1
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=3ea)

Date: 2020-10-20 11:22:16
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\DBM-Core\DBM-Core.lua line 3834:
   attempt to call method 'UpdateWarningOptions' (a nil value)
Debug:
   DBM-Core\DBM-Core.lua:3834:
      DBM-Core\DBM-Core.lua:3811
   DBM-Core\DBM-Core.lua:1342: handler()
   DBM-Core\DBM-Core.lua:856:
      DBM-Core\DBM-Core.lua:843
Locals:
self = <table> {
 CopyAllModOption = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3620
 CreatePizzaTimer = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:2650
 UnregisterShortTermEvents = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1134
 GetUnitIdFromGUID = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3332
 CopyProfile = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1991
 GetNumRealGroupMembers = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3260
 Counts = <table> {
 }
 LoadAllModDefaultOption = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3543
 DeleteProfile = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:2008
 DungeonMusic = <table> {
 }
 RegisterOnGuiLoadCallback = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:2863
 GetPlayerNameByGUID = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3197
 FireEvent = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1636
 LoadModOptions = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3390
 SCENARIO_COMPLETED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3999
 HighestRelease = 20201013010000
 GetMyPlayerInfo = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3171
 Schedule = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1941
 ADDON_LOADED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1334
 IsDev = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:103
 BattleMusic = <table> {
 }
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3091
 DeleteAllModOption = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3737
 ApplyProfile = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1976
 GetFullPlayerNameByGUID = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3193
 GetBossUnitId = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3315
 ShowRealDate = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:85
 Revision = 20201013224412
 RegisterEvents = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1011
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1196
 CopyAllModTypeOption = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3680
 FilterRaidBossEmote = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1172
 Options = <table> {
 }
 PLAYER_LEVEL_CHANGED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3536
 HudMap = <table> {
 }
 LFG_PROPOSAL_SUCCEEDED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3925
 InfoFrame = <table> {
 }
 RangeCheck = <table> {
 }
 UPDATE_BATTLEFIELD_STATUS = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3977
 SpecChanged = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3527
 CheckNearby = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3362
 Flash = <table> {
 }
 IsCreatureGUID = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3307
 strFromTime = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:740
 Unschedule = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1948
 ReleaseRevision = 20201013010000
 GetUnitCreatureId = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3279
 UPDATE_MOUSEOVER_UNIT = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:4309
 GROUP_ROSTER_UPDATE = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3082
 RegisterShortTermEvents = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1113
 ScenarioCheck = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:4206
 LOADING_SCREEN_DISABLED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:4166
 GetUnitFullName = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3176
 GetGroupMembers = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3241
 LoadModsOnDemand = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:4185
 TransitionToDungeonBGM = <function> defined @Interface
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.4.0
  Atlas, vv1.47.03.11304.00
  AtlasClassicWoW, vv1.47.02.11304.00
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.0.3
  Bartender4, v4.10.5
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BetterVendorPrice, vv1.13.07
  CharacterStatsClassic, v3.6.5
  Clique, vv1.0.3-classic
  DBMCore, v9.0.1
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=3ea)

**Comment by QartemisT** [comment]
You've installed the retail version of the client, onto classic.
