### ISSUE TITLE
Lua errors

### ISSUE THREAD

**Issue by swetlover** [DeadlyBossMods/DBM-Classic#646]
**Twitch client installed classic/retail version on retail/classic**

**Describe the bug**

RangeCheck Frame  does not appear, just  keeps getting lua errors.
**Do you have an error log of what happened?**

```lua
			["message"] = "Interface\\AddOns\\DBM-Core\\DBM-RangeCheck.lua:435: attempt to call method 'OldSetText' (a nil value)",
			["time"] = "2020/12/09 21:58:52",
			["locals"] = "InCombatSkipped",
			["stack"] = "Interface\\AddOns\\DBM-Core\\DBM-RangeCheck.lua:435: in function `SetText'\nInterface\\AddOns\\DBM-Core\\DBM-RangeCheck.lua:627: in function <Interface\\AddOns\\DBM-Core\\DBM-RangeCheck.lua:601>",
			["session"] = 5296,
			["counter"] = 797,
```
**To Reproduce**

Princess Huhuran combat get this lua errors.
**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes
**Which version of DeadlyBossMods are you using?**
1.13.63-10-gcc57ccb-classic
**Was it working in a previous version? If yes, which was the last good one?**
Can't remember, but the version used on November 28 did not have this problem.
**Additional context**
Chinese WOW client.

**Comment by MysticalOS** [comment]
That's fixed in a newer alpha version. Thanks for report
