### ISSUE TITLE
Kel'Thuzad timers

### ISSUE THREAD

**Issue by tatenjinmu** [DeadlyBossMods/DBM-Classic#648]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by QartemisT** [comment]
Invalid report, closing.

**Comment by tatenjinmu** [comment]
Good day developers of DBM!! We were doing KT and there were missing timers for things like MC void zone etc.

May it be requested to look into these timers and see if there is some issue with them not appearing or

**Comment by QartemisT** [comment]
Should have put that in the main description XD Currently classic stuff is on hold while there's retail issues at hand.

**Comment by QartemisT** [comment]
Closing as duplicated issue now XD
