### ISSUE TITLE
Kelthuzad Timer

### ISSUE THREAD

**Issue by tatenjinmu** [DeadlyBossMods/DBM-Classic#649]
First submission clicked on the wrong box for text.

Timers for MC during Kel'Thuzad fight are not appearing, and other timers in the fight do not appear (void zone, add spawn etc)

May it be requested to look into adding them or whatever issue is making them fail to appear?

Thank you.

**Comment by QartemisT** [comment]
Currently classic stuff is on hold while there's retail issues at hand.

**Comment by tatenjinmu** [comment]
My bad on the submission/double lol. 1st time i've come in to do it.

Thank you for looking into the issue when you have time.

**Comment by MysticalOS** [comment]
I recall both of those not actually being reliable timers. they literally exist in mod disabled because they were too wildly variable.

**Comment by tatenjinmu** [comment]
They do appear inside DBM and i have them on for notifications (even if its just the CD and available soon) but no bars/timers/etc appear to be working at all, which is why i brought it to note.
