### ISSUE TITLE
Four Horsemen: Mark counter always shows "Mark 0 ... "

### ISSUE THREAD

**Issue by Grookshank** [DeadlyBossMods/DBM-Classic#650]
**Describe the bug**
Mark count on 4 Horseman always shows "Mark 0 in 3 seconds" and "Mark 0". It seems the variable %d seems not to be filled.

**Do you have an error log of what happened?**
No.

**To Reproduce**
Turn on the option "Show pre warning for mark" in Classic > Naxx > Military > Four Horsemen.
Start the encounter.

**Screenshots**
No

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of DeadlyBossMods are you using?**
1.13.63

**Was it working in a previous version? If yes, which was the last good one?**
I dont know.

**Additional context**

**Comment by Grookshank** [comment]
So this looks like a client problem, that the variable does not get filled, since you removed the count now completely?

**Comment by MysticalOS** [comment]
The count is in special warnings for stacks, the soon warning can't really accurately have count anyways, where would it pull count from, your current stack+1? but what if you moved to a different side, then the soon warning would be lying. Nah it just needs to warn the cast is soon, and count will be managed by personal stack warning.

**Comment by Grookshank** [comment]
I think it was meant to count which total no. of marks the fight was on, but if that does not work, too bad. I think it was this way on private at least.
Thanks anyways for the quick help and response.
