### ISSUE TITLE
Kel'Thuzad Frost Breath does not show Target's name

### ISSUE THREAD

**Issue by Prosperityz** [DeadlyBossMods/DBM-Classic#664]
**Describe the bug**
Earlier in December, DBM would show an alert during Kel'thuzad "Frost Breath on <target name>". Recently, it says "Frost Breath on" with no name. It happened last week too, so this is the second week I've noticed the issue. I have the option to show Frost Breath target checked in my DBM settings. I also updated DBM just before raid, so it was the latest version each time.

**Do you have an error log of what happened?**
No error log but I have a screenshot, see below.

**To Reproduce**
Fight Kel'Thuzad. Wait for Frost Breath to be cast. 

**Screenshots**
![image](https://user-images.githubusercontent.com/77242514/104130668-a450d680-5337-11eb-97bb-6409711ec7b0.png)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, but it was working the first week of naxx and other people in my guild said they're having the same issue recently.

**Which version of DeadlyBossMods are you using?**
1.13.67-classic

**Was it working in a previous version? If yes, which was the last good one?**
I don't remember the version number. It would've been the one used during naxx progression week so the first week of December.

**Additional context**

**Comment by MysticalOS** [comment]
Are you playing with any chinese or russian player names and perhaps using a warning font that doesn't support these characters?

**Comment by Prosperityz** [comment]
No chinese or russian characters in our raid member's names. Does the issue happen with accent characters like "é"?

**Comment by MysticalOS** [comment]
with some fonts maybe. it'd be related to something current font could not render
