### ISSUE TITLE
lua unexpected symbol

### ISSUE THREAD

**Issue by BPsteve** [DeadlyBossMods/DBM-Classic#666]
Having random crashes on zone in. Crashed on Onyxia at this log time: 

**Do you have an error log of what happened?**

Date: 2021-01-14 00:56:23
ID: -1
Error occured in: Global
Count: 1
Message: WTF\Account\BLANK\SavedVariables\DBM-Onyxia.lua line 1:
   unexpected symbol
Debug:
   [C]: ?
   [C]: LoadAddOn()
   DBM-Core\DBM-Core.lua:4179: LoadMod()
   DBM-Core\DBM-Core.lua:4140: LoadModsOnDemand()
   DBM-Core\DBM-Core.lua:4101: func()
   DBM-Core\DBM-Core.lua:1833:
      DBM-Core\DBM-Core.lua:1824
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.0.4
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v3.7.1
  DBMCore, v1.13.67-6-g2483e48
  DBMDefaultSkin, v
  DBMOnyxia, v
  DBMStatusBarTimers, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  HealBot, v1.13.6.1
  HealBotData, v1.13.6.1
  HealBoten, v1.13.6.1
  HealBotOptions, v1.13.6.1
  HealBotTips, v1.13.6.1
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  PallyPower, vv1.2.27-classic
  Questie, v6.2.4
  RCLootCouncilClassic, v0.12.1
  Recount, vv1.13.5c
  Scrap, v9.0.1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.27
  WeakAuras, v3.1.8
  BlizRuntimeLib_enUS v1.13.6.11306 <none>
  (ck=4b4)

Date: 2021-01-14 00:56:18
ID: -5
Error occured in: Global
Count: 1
Message: WTF\Account\BLANK\SavedVariables\DBM-StatusBarTimers.lua line 1:
   unexpected symbol
Debug:
   
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.0.4
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v3.7.1
  DBMCore, v1.13.67-6-g2483e48
  DBMStatusBarTimers, v
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.6.11306 <none>
  (ck=2c7)

**To Reproduce**
Full computer crash and hard restart on zone in.

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Have disabled all add-ons except DBM

**Which version of DeadlyBossMods are you using?**
 v1.13.67-6-g2483e48

**Was it working in a previous version? If yes, which was the last good one?**
Was having similar issues in ZG and SM over the last 9 months.

**Additional context**

**Comment by MysticalOS** [comment]
Well, the lua errors themselves can't cause computer to crash, in fact it's probably other way around. whatever caused crash corrupted saved varables so now they throw lua errors. I'd delete the two files it's comcomplaining about to fix the errors (they'll be regenerated) as for the crash that's hard to say without seeing the actual crash report (if there is one). That might require getting more technical help on wow tech forums.

**Comment by BPsteve** [comment]
Thanks Adam.

Helpful to narrow down what the issue is.

Warm Regards,
Steve     On Friday, January 15, 2021, 04:26:28 PM EST, Adam <notifications@github.com> wrote:  
 
 


Well, the lua errors themselves can't cause computer to crash, in fact it's probably other way around. whatever caused crash corrupted saved varables so now they throw lua errors. I'd delete the two files it's comcomplaining about to fix the errors (they'll be regenerated) as for the crash that's hard to say without seeing the actual crash report (if there is one). That might require getting more technical help on wow tech forums.

**Comment by QartemisT** [comment]
Marking as resolved.
