### ISSUE TITLE
Function "checkForSafeSender" non-bnet friend check doesn't work.

### ISSUE THREAD

**Issue by Winsane** [DeadlyBossMods/DBM-Classic#676]
The reason is because the C_FriendList.GetFriendInfo() function is for getting friend info by name, not by index.
It was fixed in the non-classic version in the last update.
Classic (broken):
https://github.com/DeadlyBossMods/DBM-Classic/blob/8c32c0c198a0d35b591ea71cfebb853900f10cf1/DBM-Core/DBM-Core.lua#L565-L576

Retail (working):
https://github.com/DeadlyBossMods/DeadlyBossMods/blob/f8b6647bbb9580887cd39e1e3aeca4a64b2f1833/DBM-Core/DBM-Core.lua#L657-L665

**Comment by MysticalOS** [comment]
Did they change it? because it literally all used to work fine.

**Comment by QartemisT** [comment]
Reference commit on retail: https://github.com/DeadlyBossMods/DeadlyBossMods/commit/e4eac7f634795e5fab772a6d7cbd08502fef810e#diff-252066875e001ef49f0f17062ee1b89bf2197442bbfbc6aafbc78a279288c667

**Comment by Winsane** [comment]
> Did they change it? because it literally all used to work fine.

They did, but I can't find any documentation of when exactly it was changed. It seems like "GetFriendInfo" used to be for getting by index, but was changed to getting by name and replaced by "GetFriendInfoByIndex" at some point.
