### ISSUE TITLE
Four Horsemen Mark out of sync

### ISSUE THREAD

**Issue by E-Hansson** [DeadlyBossMods/DBM-Classic#689]
**Describe the bug**
When 1 or more of the four horsemen are dead mark bars are spawning too often. This seriously cripples the usage of the mark bars (which otherwise is wonderful for synchronisation). The expected behaviour is that the mark bars continues to happen according to the periodic behaviour of the living bosses. Not a combination of the two (effectively causing multiple of periodicity to be scheduled in parallel).

**Do you have an error log of what happened?**
No error logs. However, logs from battles (e.g. just grabbed a random fight: https://classic.warcraftlogs.com/reports/39yAHRnvFQrt8ap6#fight=11&type=auras&spells=debuffs&view=events&eventstart=1293324) shows that when a boss dies his mark gets out of synch and any potential from the spirit then follows his 12-13 sec cd. In the example, see time points 00:03:48.484 (a "standard period cast"), 00:03:55.374 (a newly spawned "dead period cast") and 00:04:01.426 (the next "standard period cast").

**To Reproduce**
1. Do the fight four horsemen with standard config on DBM.
2. Let someone get afflicted with a mark from a spirit that wasn't killed in synch with the "standard mark period cast".
3. An extra mark bar have now appeared (unless the new period is to close to the original, not sure about the time frame of the `self:AntiSpam(5)`)?

**Screenshots**
None taken.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
DBM was active along with a custom hook to DBM timers (more or less a regex on the text on bars and a few small operations).

**Which version of DeadlyBossMods are you using?**
Latest from curseforge.

**Was it working in a previous version? If yes, which was the last good one?**
Not that I'm aware of.

**Additional context**
Unaware of what is asked with this heading.

**Potential solutions**
The issue is the assumption that the periods are always the same. However, it seems like there can be up to 4 different periods based the logs I've gone over. The original period is of most interest though. Hence, I propose that (in my own preferens order):

1. Only the original period is shown. This can be achieved with an internal timer so that one only reacts to marks cast 11.5s after the previous mark and keep the spam filter. Here 11.5s is taken as an assumed safe delay (the marks shouldn't even with potential server and communication overheads) be cast more frequently. (simple solution `if mark and self:AntiSpam(5) and time() - previous_mark_at >= 11.5 then [...] previous_mark_at = time()`, sure one could to a more advanced with a predictive model of the original period and calculating the probability of a mark not being part of that model but that's most likely overkill.)
2. Spawn 1 bar per mark since each type of mark are regular with regards to their own period (one can see the synchronised periods as a special case that only happens at the start of a fight).

I propose the first option since it's the one that resembles the current behaviour most while being "correct". Hence, it will not change the behaviour significantly unlike the second option.

**Comment by E-Hansson** [comment]
Can you please explain why it was closed with no comments?

**Comment by QartemisT** [comment]
It wsas closed with a commit, that resolved the issue :)

**Comment by MysticalOS** [comment]
I already carefully reviewed log and saw it was easiest to just filter out casts by spirits by tying casts specifically to living horseman creature Ids. It'll now only show mark casts/bar for them and not spirits.

**Comment by E-Hansson** [comment]
Ah thanks missed the commit, been a while since I collaborated on Github :)

However, just filtering on spirit has a drawback. From the logs (an "none-original period"):
```
00:03:55.374 | Efoclaw is afflicted by  Mark of Mograine (2) from Highlord Mograine |  
-- | -- | --
00:03:55.374 | Atwahilate is afflicted by  Mark of Mograine from Spirit of Mograine
```
It looks like the bosses does a last effort Mark sometimes before dying.

**Comment by MysticalOS** [comment]
Changed antispam period to 10. is it 100% resolved, no. But like 95% at this point.

**Comment by E-Hansson** [comment]
Don't sell it short, with a 10 second period where from which no events are considered the worst case scenario (in terms of offset from original period) can be shown as follows.
Let P be the period time (CD time) and s an arbitrary time point where marks are cast according to original schedule then the following is the worst case in terms of offset from the original period s + n*P:

[s] Original Mark -> Bar
[s+10+e] Boss death, Mark -> Bar (offset: P-10 early)
[s+P] Original Mark -> nil
[s+20+e] Boss death, Mark -> Bar (offset: 2P-20 early)
[s+2*P] Original Mark -> nil
[s+30+e] Boss death, Mark -> Bar (offset: 3P-30 early)
[s+3*P] Original Mark -> nil
[s+4*P] Original Mark -> Bar

Note that 3P-30 < 10 if P to range between 11 and 13 to be on the safe side with noise in the casting period. This means that even in the worst case the bar will readjust to the original period after one cycle. And the worst case is really really unlikely (killing three bosses just above 10 seconds after each other and the first being just about P-10s before a mark is cast).

So I would say that it is as good as it can get. Without knowing ahead when the next mark should be cast (when considering noise) it is impossible to do 100% correct. Sure one can tune the 10 a bit higher but too much and one risks blocking a mark according to the original schedule instead.

Thanks a lot for the fast fix!
