### ISSUE TITLE
"Mark xx" goes out of sync after one or more bosses die on 4 Horseman in Naxxramas

### ISSUE THREAD

**Issue by fleetcommand** [DeadlyBossMods/DBM-Classic#694]
**Twitch client installed classic/retail version on retail/classic**
(Classic version installed from CurseForge)

**Describe the bug**
During the 4 Horsemen fight, the addon is counting the upcoming marks in a form of some castbars "Mark 1", "Mark 2". It is working perfectly, until one or more of the bosses die. After that, the mark castbars start "hurrying".

**Do you have an error log of what happened?**
N/A

**To Reproduce**
1. Make sure you have the "Show timer for next horseman's Mark (with count)" option enabled
2. Go to 4 Horsemen
3. Observe that the castbars for the marks are working in sync with the bosses and with the actual marks
4. Wait until one or more bosses die out of the four
5. Observe that the castbars are going faster than before

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Not yet, did not want do disable addons (especially raidframes (ShadowedUI)) during live raid, but if it is required, please let me know

**Which version of DeadlyBossMods are you using?**
DBM-Core-1.13.69-classic

**Was it working in a previous version? If yes, which was the last good one?**
No, as this is a relatively new feature

**Comment by MysticalOS** [comment]
Closing as duplicate, this is already addressed in alpha
