### ISSUE TITLE
DBM:IsShadowlands() undefined in that scope

### ISSUE THREAD

**Issue by Road-block** [DeadlyBossMods/DBM-Classic#695]
**Describe the bug**
Latest DBM-Classic alpha 1.13.69-20-gd20a301 errors on load for the live 1.13.6 Classic WoW Client. (enUS)

**Do you have an error log of what happened?**
```
1x DBM-Core\DBM-Core-1.13.69-20-gd20a301.lua:4762: attempt to call method '?' (a nil value)
DBM-Core\DBM-Core-1.13.69-20-gd20a301.lua:4762: in main chunk
```
then after the core breaks a slew of errors follow
```
1x DBM-Core\DBM-Core-1.13.69-20-gd20a301.lua:3903: attempt to call method 'UpdateWarningOptions' (a nil value)
DBM-Core\DBM-Core-1.13.69-20-gd20a301.lua:3903: in function <DBM-Core\DBM-Core.lua:3879>
DBM-Core\DBM-Core-1.13.69-20-gd20a301.lua:1389: in function 'handler'
DBM-Core\DBM-Core-1.13.69-20-gd20a301.lua:890: in function <DBM-Core\DBM-Core.lua:877>
```
```
1x DBM-LogoutTimer\localization.en.lua:1: attempt to call method 'GetModLocalization' (a nil value)
DBM-LogoutTimer\localization.en.lua:1: in main chunk
```
```
1x DBM-LogoutTimer\LogoutTimer.lua:1: attempt to call method 'NewMod' (a nil value)
DBM-LogoutTimer\LogoutTimer.lua:1: in main chunk
```
```
6x (null)
```

**To Reproduce**
Just login with the latest alpha enabled.

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**
1.13.69-20-gd20a301-classic
 

**Was it working in a previous version? If yes, which was the last good one?**
previous alpha 1.13.69-18-gae8b609-classic didn't error.

**Additional context**

**Comment by QartemisT** [comment]
PR stuck in with fix, will be resolved soon as Adam is awake :)

And yes, the errors after are a result of the original issue (And not of DBM-LogoutTimer) :P
