### ISSUE TITLE
crash at login

### ISSUE THREAD

**Issue by Sabbaer** [DeadlyBossMods/DBM-Classic#697]
**Describe the bug**

full crash of dbm when login
**Do you have an error log of what happened?**
Date: 2021-03-13 13:53:21
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\DBM-Core\DBM-Core.lua line 4762:
   attempt to call method '?' (a nil value)
Debug:
   DBM-Core\DBM-Core.lua:4762: in main chunk
Locals:
L = <table> {
 AUTO_VOICE_OPTION_TEXT = "Spiele gesprochene Warnungen für $spell:%s"
 INSTANCE_INFO_STATS_AWAY = "Abwesend: %s"
 AUTO_RRANGE_OPTION_TEXT = "Zeige inverses Abstandsfenster (%sm) für $spell:%s"
 MIDDLE = "Mitte"
 OUT_OF_DATE_NAG = "Deine Version von Deadly Boss Mods ist veraltet. Du solltest eine Aktualisierung für diesen Kampf durchführen, da du sonst wichtige Warnungen oder Timer verpassen könntest oder automatische "Schreie" fehlen, die der Rest deines Schlachtzuges von dir erwartet."
 VERSIONCHECK_ENTRY_TWO = "%s: %s (%s) und %s (%s)"
 MPROFILE_COPY_SUCCESS = "Mod-Einstellungen von %s (Spez. %d) wurden kopiert."
 INSTANCE_INFO_ALL_RESPONSES = "Antworten von allen Mitgliedern des Schlachtzuges erhalten"
 OPTION_CATEGORY_WARNINGS_ROLE = "Rollenansagen"
 TIMER_FORMAT_MINS = "%d |4Minute:Minuten;"
 ANNOUNCE_PULL_TARGET = "Pulle %s in %d Sekunden. (gesendet von: %s)"
 POISON_ICON = ""
 BIG_ADD = "Big Add"
 ADDS = "Adds"
 BOSS = "Boss"
 SAFE = "Sicher"
 LAG_FOOTER = "Keine Antwort: %s"
 PROFILE_APPLIED = "Profil '%s' angewendet."
 ROOM_EDGE = "Rand des Raums"
 SILENTMODE_IS = "SilentMode is "
 RANGECHECK_HEADERT = "Range Check (%dy-%dP)"
 FAR_AWAY = "Weit weg"
 GEAR_WARNING = "Warnung: Prüfe deine Ausrüstung. Deine angelegte Gegenstandsstufe ist um %d niedriger als die in deinen Taschen."
 AUTO_YELL_OPTION_TEXT = <table> {
 }
 RANGECHECK_RHEADER = "R-Range Check (%dy)"
 RANGERADAR_HEADER = "Abstand:%dm Spieler:%d"
 VOICE_COUNT_MISSING = "Für die Countdown-Stimme %d ist ein Sprach-/Zählpack ausgewählt, der nicht gefunden werden konnte. Die Stimme wurde auf die Standardeinstellung zurückgesetzt: %s."
 LOAD_MOD_COMBAT = "Laden von '%s' verzögert bis du den Kampf verlässt."
 OUTDATEDRLT = "WARNING: DBM-RaidLeadTools breaks DBM. DBM-RaidLeadTools is no longer supported and must be removed for DBM to function properly."
 SOUNDKIT_MIGRATION = "One or more of your warning/special warning sounds were reset to defaults do to incompatability with patch 8.2 and later (sound must reside in interface folder to play by path, or use SoundKit ID)"
 LOAD_MOD_TOC_MISMATCH = "%s could not be loaded because it is not designed for Classic WoW. You likely installed a retail version of a module. Remove this module and use only addons designed for Classic World of Warcraft"
 RANGECHECK_OPTION_FRAMES = "Fenster"
 PROFILE_DELETED = "Profil '%s' gelöscht. Profil 'Default' wird angewendet."
 MYTHIC_ICON = ""
 HEALER_ICON = ""
 BOSS_DOWN_NR = "%s besiegt nach %s! Das ist ein neuer Rekord! (Der alte Rekord war %s.) Das war dein %d. Sieg."
 RANGECHECK_SOUND_1 = "Standard-Sound"
 OUTDATEDSPELLTIMERS = "WARNING: DBM-SpellTimers breaks DBM and must be disabled for DBM to function properly."
 RANGECHECK_SOUND_OPTION_1 = "Sound, falls ein Spieler in Reichweite ist"
 BREAK_SEC = "Pause endet in %s Sekunden!"
 TRANSCRIPTOR_LOG_START = ""Transcriptor"-Aufzeichnung gestartet."
 NOTE_SHARE_SUCCESS = "%s hat die Notiz für %s geteilt."
 NEXT = "Nächste %s"
 UNKNOWN = "unbekannt"
 RANGECHECK_SOUND_0 = "Kein Sound"
 GENERIC_WARNING_BERSERK = "Berserker in %s %s"
 HEALER_ICON_SMALL = ""
 GENERIC_WARNING_OTHERS2 = "und %d anderen"
 SOUTH = "Süden"
 COMBAT_ENDED_AT = "Kampf gegen %s (%s) hat nach %s aufgehört."
 GUILD_BOSS_DOWN = "%s wurde durch deine Gilde besiegt nach %s!"
 RANGECHECK_OPTION_BOTH = "Zeige beide Fenster"
 NO_ARROW = "Der Pfeil kann in Instanzen nicht genutzt werden."
 AUTO_VOICE2_OPTION_TEXT = "Spiele gesprochene Warnungen für Phasenwechsel"
 MPROFILE_COPYS_S_ERROR = "Quelle korrupt. Die Soundeinstellungen oder Notizen wurden nicht oder unvollständig kopiert. Kopieren fehlgeschlagen."
 LDB_CAT_MOP = "Mists of Pandaria"
 AUTO_ANNOUNCE_TEXTS = <table> {
 }
 MINIMAP_TOOLTIP_FOOTER = "Shift gedrü
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.8
  AtlasLootClassicData, vv1.5.8
  AtlasLootClassicDungeonsAndRaids, vv1.5.8
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v3.7.3
  Combuctor, v9.0.2
  DBMCore, v1.13.69-20-gd20a301
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_deDE v1.13.6.11306 <none>
  (ck=31d)
----------------------------2nd ------------------------
Date: 2021-03-13 13:53:21
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\DBM-Core\DBM-Core.lua line 3903:
   attempt to call method 'UpdateWarningOptions' (a nil value)
Debug:
   DBM-Core\DBM-Core.lua:3903:
      DBM-Core\DBM-Core.lua:3879
   DBM-Core\DBM-Core.lua:1389: handler()
   DBM-Core\DBM-Core.lua:890:
      DBM-Core\DBM-Core.lua:877
Locals:
self = <table> {
 CopyAllModOption = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3686
 GetNumGuildPlayersInZone = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3163
 UnregisterShortTermEvents = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1181
 GetUnitIdFromGUID = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3401
 CopyProfile = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:2017
 GetNumRealGroupMembers = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3329
 Counts = <table> {
 }
 LoadAllModDefaultOption = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3609
 DeleteProfile = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:2034
 UnregisterInCombatEvents = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1116
 RegisterOnGuiLoadCallback = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:2899
 GetPlayerNameByGUID = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3266
 FireEvent = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1670
 LoadModOptions = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3459
 TransitionToDungeonBGM = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:4062
 HighestRelease = 20210216000000
 GetMyPlayerInfo = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3241
 Schedule = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1967
 ADDON_LOADED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1381
 ShowPizzaInfo = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:2713
 BattleMusic = <table> {
 }
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3134
 DeleteAllModOption = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3805
 ApplyProfile = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:2002
 GetFullPlayerNameByGUID = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3262
 GetBossUnitId = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3384
 ShowRealDate = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:86
 Revision = 20210312214441
 RegisterEvents = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1058
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1243
 CopyAllModTypeOption = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3747
 FilterRaidBossEmote = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1219
 CHARACTER_POINTS_CHANGED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3985
 SpecChanged = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3593
 CheckNearby = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3431
 Options = <table> {
 }
 Unschedule = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:1974
 ReleaseRevision = 20210216000000
 GetUnitCreatureId = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3348
 LoadModDefaultOption = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3649
 HudMap = <table> {
 }
 GetGroupId = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3270
 InfoFrame = <table> {
 }
 LOADING_SCREEN_DISABLED = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:4163
 GetUnitFullName = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3245
 GetGroupMembers = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3310
 RangeCheck = <table> {
 }
 Flash = <table> {
 }
 AddDefaultOptions = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3449
 strFromTime = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:719
 GetRaidUnitId = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:3207
 UPDATE_MOUSEOVER_UNIT = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:4291
 LoadGUI = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:2836
 DefaultOptions = <table> {
 }
 Bars = <table> {
 }
 LoadModsOnDemand = <function> defined @Interface\AddOns\DBM-Core\DBM-Core.lua:4181
 GetPlayerGUIDByName = <function
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.8
  AtlasLootClassicData, vv1.5.8
  AtlasLootClassicDungeonsAndRaids, vv1.5.8
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v3.7.3
  Combuctor, v9.0.2
  DBMCore, v1.13.69-20-gd20a301
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_deDE v1.13.6.11306 <none>
  (ck=31d)

**To Reproduce**
just log in, its a german account

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes, it still will not load 

**Which version of DeadlyBossMods are you using?**
1.13.69-20-gd20a301-classic
**Was it working in a previous version? If yes, which was the last good one?**
the previous one before the one i mentioned above

**Comment by QartemisT** [comment]
Duplicate of #695.

PR has been put in, waiting on Adam to be awake :)

**Comment by Sabbaer** [comment]
oh this is the same kk, wasnt sure
