### ISSUE TITLE
Question: Custom code

### ISSUE THREAD

**Issue by Scruudje** [DeadlyBossMods/DBM-Classic#701]
I need a line of code that cancels a timer, but not just for me:

"DBM.Bars:CancelBar("Hello") "

This cancels any timer bar with the name "Hello", however it only does it for myself. What line of code would broadcast the cancellation of the timer so it would be removed from the list of bars for anyone in my raidgroup?

**Comment by QartemisT** [comment]
There is (as far as I'm aware) a way to send a sync to cancel a bar.
If you're writing a custom mod, you will need to add custom sync handlers for this. I can help you further on the discord if you DM me :)
