### ISSUE TITLE
LibDurability error

### ISSUE THREAD

**Issue by Road-block** [DeadlyBossMods/DBM-Classic#702]
**Describe the bug**

**Do you have an error log of what happened?**
```
244x integer overflow attempting to store -nan(ind)
[C]:: ?
...DBM-Core\Libs\LibDurability\LibDurability-1.lua:54: in function <...DBM-Core\Libs\LibDurability\LibDurability.lua:47>
```

**To Reproduce**
I believe this happens when the raid unequips all slots with durability (neck/rings/trinkets/cloak) at least everyone in my group got spammed with errors when we stripped for a skip.

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**
1.13.69-29-g38a2c7c-classic alpha for me, but I think large part of my raid was on latest release version so probably not a version specific issue.

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by Road-block** [comment]
https://www.curseforge.com/wow/addons/libdurability has no issue tracker or comments enabled

**Comment by QartemisT** [comment]
The developer of that library has been notified, and we'll keep this updated if and when we hear any more; @Funkydude.

**Comment by funkydude** [comment]
@QartemisT Thanks for the ping!
@Road-block Thanks for the detailed report. Reproduced the issue and fixed it. It will be included automatically in the next DBM version.

**Comment by QartemisT** [comment]
Closing as will be built automatically in the next alpha :)
