### ISSUE TITLE
always out of date after update. can not up date to 1.13.72

### ISSUE THREAD

**Issue by chairmanqin** [DeadlyBossMods/DBM-Classic#726]
**Describe the bug**

i installed 1.13.72, CurseForge shows dbm 1.13.72 is installed. but i got 1.13.70 in game, and force disabled itself.

**Do you have an error log of what happened?**
no

**To Reproduce**

1.downloaded 1.13.72 from curse and wowinterface, 
2.delete old dbm, 
3.install 1.13.72 to /addons, 
4.login game, got dbm 1.13.70(2021/03/23 16:54:28)

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**
i installed 1.13.72, but dbm said its 1.13.70
**Was it working in a previous version? If yes, which was the last good one?**
yes, 1.13.71 i think
**Additional context**

**Comment by MysticalOS** [comment]
likely have two or more copies of wow installed. you likely are not using the addons folder that curseforge is updating for you., if it says you have .70 that's what you have installed
