### ISSUE TITLE
Bars can no longer be positioned flush with top of screen

### ISSUE THREAD

**Issue by SucculentVeal** [DeadlyBossMods/DBM-Classic#728]
**Describe the bug**
I like to have my dbm bars positioned flush with the top edge of my screen. as of about 1 month ago you can no longer position the bars close enough to the top edge of the screen for my liking.

**Do you have an error log of what happened?**
No

**To Reproduce**
set bars to expand downwards, attempt to align bar with top edge of screen.

**Screenshots**
Screenshot 1 - Desired positioning of bars.
![WoWScrnShot_042821_024449](https://user-images.githubusercontent.com/83301365/116281133-beba9d00-a7cc-11eb-9dd1-5635b58fd8ce.jpg)
Screenshot 2 - Bars can not be positioned higher than shown.
![WoWScrnShot_042821_024626](https://user-images.githubusercontent.com/83301365/116281174-c7ab6e80-a7cc-11eb-8db6-f3b8315527d6.jpg)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
nope

**Which version of DeadlyBossMods are you using?**
DBM-Core-1.13.72-classic.zip

**Was it working in a previous version? If yes, which was the last good one?**
Last worked as of DBM-Core-1.13.69-classic.zip

**Additional context**
Ty for looking into this.

xoxo SucculentVeal

**Comment by QartemisT** [comment]
Use the latest alpha version of the addon, where we've fixed this :)
