### ISSUE TITLE
Warning stop on Crommagus after 2nd breath

### ISSUE THREAD

**Issue by fireboy92k** [DeadlyBossMods/DBM-Classic#736]
**Describe the bug**
In BWL on 5/29 multiple folks in our raid confirmed that DMB is only alerting on the first 2 breaths.  After the second one, alerts stop.

**Do you have an error log of what happened?**
no errors reported

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**  no, but I don't know the addon stack for others.  Almost everyone in the 40man confirmed the issue.

**Which version of DeadlyBossMods are you using?**  latest classic version

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
Old issue but truth of matter, in all these months no one else reported it, and I could not confirm issue myself. In fact I watched all warnings work just fine on DBM on stream earlier tonight so closing issue.
