### ISSUE TITLE
Classic ERA - Nefarian class call timers

### ISSUE THREAD

**Issue by Slivo-fr** [DeadlyBossMods/DBM-Classic#766]
**Describe the bug**
The class calls timers bars doesn't show up 

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of DeadlyBossMods are you using?**
DBM 1.14.14 alpha (2022/02/08 17:12:04)

**Was it working in a previous version? If yes, which was the last good one?**
Was working a week earlier, I can't remember the version but I was up to date

**Comment by Slivo-fr** [comment]
Here is some french strings for some calls :

> Nefarian crie : Guerriers, je sais que vous pouvez frapper plus fort que ça ! Voyons ça !

> Nefarian crie : Voleurs, arrêtez de vous cacher et affrontez-moi !

> Nefarian crie : Les paladins… J'en entendu dire que vous aviez de nombreuses vies… Montrez-moi.

> Nefarian crie : Les mages aussi ? Vous devriez être plus prudents lorsque vous jouez avec la magie.

> Nefarian crie : Ah, les chasseurs et les stupides sarbacanes !

> Nefarian crie : Les druides et leur stupides changements de forme. Voyons ce qu'ils donnent en vrai…

I don't know if that might help, but DBM actually detected the Paladin call without showing the bars, probably because of the buff as I was the tank and had Nefarian as target ? 

> <Nefarian>   L'appel de Paladin

**Comment by MysticalOS** [comment]
it doesn't care who your target is or buffs. it detects yell, it starts a bar, doesn't detect yell doesn't start it.

is everyone on french client in. your raid? nef has pretty much never had french support, if it workd in past it was because you used to have someone in raid playing a supported language (and they sent a sync to rest of you). if that's not case this week then it'd definitely not be working for you.

**Comment by Slivo-fr** [comment]
I have no idea, but I do think some are using the english client, I'll ask.
Any chance to add the french support ? :D

**Comment by MysticalOS** [comment]
if those strings taken directly from chat log and accurate, you bet we'll add em :)

**Comment by Slivo-fr** [comment]
They are ! 
We miss two calls however, I'll try to get them next week

**Comment by MysticalOS** [comment]
Actually have all the french strings right already surprisingly, so the issue is actually something else.

I'm starting to wonder if something else going on. when you saw these messages, what color were they? were they yell text (red), emote text (orange) or emphasized emote text (Yellow)

**Comment by Slivo-fr** [comment]
Oh nice :D

It was yells

**Comment by MysticalOS** [comment]
Then I'm still at a loss why it didn't work. At this point the fight needs to be logged with an addon called Transcriptor. it can be downloaded from here for classic: https://www.curseforge.com/wow/addons/transcriptor/files/2807299

when instlaled, before you pull boss just do /transcriptor to start the log, when pull is over do it again to stop the log later (after you've logged out) just go into WTF folder (not addons) and locate the saved variable file named transcriptor.lua and share that there.

**Comment by Slivo-fr** [comment]
I will, thanks

**Comment by MysticalOS** [comment]
No, thank you. I definitely want to get this issue solved. It's good feedback that allows us to make sure everything works right.

**Comment by Slivo-fr** [comment]
The addon outputs some LUA errors, let's hope it's working properly :/

**Comment by Slivo-fr** [comment]
Here is one pull, another one coming soon https://ufile.io/hoz79f95

**Comment by Slivo-fr** [comment]
And another one https://ufile.io/oicvxls4
Both 30 days lifetime

**Comment by Slivo-fr** [comment]
May I provide anything else to help with this issue ?

**Comment by MysticalOS** [comment]
it wasn't fixed by making syncing super aggressive?

At this point I'm just gonna label issue unsolvable. We didn't change anything. it worked before, now it doesn't. it has to be a problem on blizzards end. Maybe they are just outright blocking comms and there is nothing we can do about that.

**Comment by Slivo-fr** [comment]
Didn't the log helped at all ?
It still doesn't work yeah :(

**Comment by MysticalOS** [comment]
There is literally nothing wrong at our end. We have correct translations. There is no reason DBM shouldn't detect the boss yells, the problem is the comms are gettnig blocked somewhere.

we could try removing comms all together and simply hope raiders are playing in a language DBM supports and maybe that'd work but beyond that I have no further ideas.

**Comment by Slivo-fr** [comment]
But you said french was supported earlier, isn't it ?

**Comment by Slivo-fr** [comment]
By the way, I got some more feedback from players, at least two of them are playing with the EN client and none of them had the timers displayed as well.
ERA is sometimes affected by SoM design changes because reasons, has something specific been done for detecting class calls on SoM ?

**Comment by MysticalOS** [comment]
Nothing changed with detecting it what so ever, still yells, which remain unchanged. if I had to guess, it's because of sync throttling cuased by other addons, especially libhealcomm

**Comment by Slivo-fr** [comment]
I will try out the alpha on next raid thanks !
Let me know if I can help in any way

**Comment by Slivo-fr** [comment]
Does work properly now, I've finally been able to try it out !
Thanks !
