### ISSUE TITLE
Getting a Lua error every time I log on or reload

### ISSUE THREAD

**Issue by Jokaleth** [DeadlyBossMods/DBM-Classic#768]
![image](https://user-images.githubusercontent.com/87456827/198850621-07168161-9842-4df5-9c94-018cf77a1aac.png)

Not much else to say as the title really says it all.

DBM Version: "DBM-3.4.18-5-g506f923-wrath"

**Comment by MysticalOS** [comment]
Something went wrong with packaging only on that file. the files after and before it are fine. just don't use that file. I'll go ahead and delete it from download
