### ISSUE TITLE
Option to switch Chat Tab where DBM posts is Messages

### ISSUE THREAD

**Issue by Serverfrog** [DeadlyBossMods/DBM-Classic#769]
**Is your feature request related to a problem? Please describe.**
Currently DBM only posts in the General Chat Tab.
This one is used for many other things and addons which means it get quite cluttered.
So many use a separate chat tab for more Important things. Specially in Raids.
This is were DBM then wont post and you cant see it. 

**Describe the solution you'd like**
An Option to select in which of the Chat tab DBM Messages get posted

**Describe alternatives you've considered**
Misuse one of the Channels like Whisper as Option. but it would be quite bad to use it that way

**Additional context**
It would really help to split clutter from Important things like DBM

**Comment by MysticalOS** [comment]
https://github.com/DeadlyBossMods/DBM-Retail/wiki/%5BAdvanced-Guide%5D-Custom-Chat-Tab

**Comment by Serverfrog** [comment]
seems like this does not work in Classic as i did that, reloaded, etc and it still post everything in the General Chat.
Also a Little UI option to set it would be much more comfortable

**Comment by MysticalOS** [comment]
I remember we tried adding it to UI once, the problem is fetching all chat tabs is ugly as sin and can change between sessions.

For example, while visually your tabs look same, they may be numbered differently in api so next login messages start appearing in a diff tab than what you set. Maybe this has improved over the years though and is worth revisit.

**Comment by Serverfrog** [comment]
As i see Addons like TSM or ElvUI having this option, it seems it should be quite possible that way. Thats also the Reason i even proposed it ;) if i didn't saw it in other Addons, it would not come to my mind!
