### ISSUE TITLE
Deadly BM incompatiable

### ISSUE THREAD

**Issue by Stephen1960A** [DeadlyBossMods/DBM-Classic#771]
**Describe the bug**

DBM to be compatiable

**Do you have an error log of what happened?**

Installed latest version - not compatiable 
Playing WOLK classic on Macbook Air M2 chip

**To Reproduce**
install - sya not compatible and does not work 
-->

**Screenshots**
[Untitled.pdf](https://github.com/DeadlyBossMods/DBM-Classic/files/12045980/Untitled.pdf)

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of DeadlyBossMods are you using?**
Latest 3.4.,2

**Was it working in a previous version? If yes, which was the last good one?**
yes

**Additional context**

**Comment by MysticalOS** [comment]
you installed retail version on classic, that's why. install correct version of mod for wrath classic (after removing all those retail modules)

**Comment by Stephen1960A** [comment]
Hi Thanks for the prompt reply - I have downloaded and installed DBM-3.4.44-wrath.zip I still get the system saying DBM is incompatible Is that not the correct version ?Any help is appreciated CheersStephen WiseOn 14 Jul 2023, at 16:02, Adam ***@***.***> wrote:you installed retail version on classic, that's why. install correct version of mod for wrath classic (after removing all those retail modules)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
