### ISSUE TITLE
1.15 Wow Classic Era AQ40 Anubisath Defender Plague Effect

### ISSUE THREAD

**Issue by rctfenix** [DeadlyBossMods/DBM-Classic#777]
1.15 Wow Classic Era AQ40 Anubisath Defender Plague Effect

**Describe the bug**

DBM mod is not properly calling out the Plague effect from the Anubisath Defender's in the hallway after Huhuran. Tried switching out spell ID's to 26556 and 22997 with no luck in resolution.

**Comment by mimixy** [comment]
in AQ20 the plague triggers the appropriate DBM alert (ads in ossi room). but not working in aq40 on ads post huhuran

**Comment by MysticalOS** [comment]
26556 should work, gonna guess you missed a spot changing it
