### ISSUE TITLE
SoD Blackfathom buff spam

### ISSUE THREAD

**Issue by DaMaGepyHUN** [DeadlyBossMods/DBM-Classic#780]
**Is your feature request related to a problem? Please describe.**
I recently updated DBM and ppl from guild asking me to disable DBM buff announcements because they keep getting annoying worldbuff messages every 5-10 second at each Blackfathom WB I catch in Darnassus.

**Describe the solution you'd like**
I found no option for it to disable it
So I had to manyually comment out the specific line in:
DBM-Core\DBM-Core.lua:5021
--SendWorldSync(self, 4, "WBA", "Blackfathom\tBoth\t430947\t6\t4")

But its not a real solution because then someone else's client will continue to spam this. Should be disabled by default (its very short timered buff anyway) and maybe add a checkbox for it to turn it on. Thought announcing it is totally useless and goes out every 5-10 second at peak server time.

**Comment by QartemisT** [comment]
The latest alpha now has this disabled, and may be re-enabled in future if it is less spammy.
