### ISSUE TITLE
Combat start timer question

### ISSUE THREAD

**Issue by mimixy** [DeadlyBossMods/DBM-Classic#783]
Hey there. Since chatting about the vael combat start timer yesterday, I have a query about 2 other combat start timer.

Ragnaros in MC has a combat start timer, and is trigerred when the RP is initiated. The initial timer isn't accurate however, and can be off by 10s or so. However that is normally fixed when Rag kills Domo, and then timer then resets to 10 seconds which is accurate. Is there any way for the initial timer to be more accurate, or is this the best it can be? This isn't a big deal at all, since as I said, the timer resets to 10s after Domo gets killed, which is always accurate. 

Second one is Saphiron in Naxx. Saph doesn't have a combat start timer currently. Once you enter the room, Saph does some RP spawning animation, spawns and then combat starts. That's one fight that a combat start timer can be useful, especially the tank to use CD's accordingly right before combat starts. However I think the problem with that fight is there are no RP lines in chat you can use as a trigger? So not sure how to trigger combat start timer there. Maybe that's why you haven't implimented one for Saph :)

**Comment by MysticalOS** [comment]
they were ALL bugged, all except ragnaros

**Comment by mimixy** [comment]
Oh so saph was always meant to have one, but due to the bug (you fixed), that timer never showed up for us? Meaning we now have a saph combat start timer too?

**Comment by MysticalOS** [comment]
the RP on ragnaros is highly varaible, it can actually be anywhere between like 68-82. DBM used to use low estimation but classic players complaiend a lot, so now it uses the high estimate but yes as you say as soon as domo dies it auto corrects cause that's exactly 10 seconds

**Comment by MysticalOS** [comment]
Well no, saph can't have one cause there is no event for it as far as I know. no boss yell or combat log event to the bones forming. but about 29 combat start timers across various bosses were broken since 2 months ago.

**Comment by mimixy** [comment]
that's great news. i look forward to experiencing all the 'new' combat timers. thank you!
