### ISSUE TITLE
Corrupted Mind tracker on Loatheb not working

### ISSUE THREAD

**Issue by cokesplash** [DeadlyBossMods/DBM-Classic#784]
**Describe the bug**
On Loatheb, DBM tracks healers with the Corrupted Mind debuff in a frame. This is no longer working since hardcore I believe. 

**Do you have an error log of what happened?**
There is no error, timers just stay at 0. 

**To Reproduce**
Fight Loatheb and cast a heal. Players get corrupted mind but the frame doesn't work.

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No - hard to do in raid.

**Which version of DeadlyBossMods are you using?**
1.15

**Was it working in a previous version? If yes, which was the last good one?**
Yes it has always worked until hardcore.

**Additional context**

**Comment by MysticalOS** [comment]
Probably yet another case of invalid spellIds, no time to check them right now so it'll be fixed when I get to it

**Comment by cokesplash** [comment]
Can we do a pull req with the fix for you?

**Comment by cokesplash** [comment]
I am told the fix has been submitted here:

https://github.com/DeadlyBossMods/DBM-BCVanilla/pull/92

**Comment by MysticalOS** [comment]
Yes it was already merged, but didn't make it in last update so it's in alpha/mext update, forgot to close issue

**Comment by cokesplash** [comment]
Sorry to reopen this, just curious if this update went out already (because if it did, our fix didn't work). 
If not, do you have an ETA for it?

**Comment by MysticalOS** [comment]
I assumed your updates were tested. It's only reason I even merged them. If you do a PR and it's not tested, please mark it as draft.

I simply don't have any means of doing in there and testing it myself for that boss since it's exclusive to era so I don't see it getting fixed any time soon so I may just go ahead and delete that infoframe if it doesn't work.

**Comment by cokesplash** [comment]
Hey,
I didn't do the fix myself so can't speak to that, although I trust Eblis (mikinho) to fix things properly, he is constantly fixing era addons for authors. On his thread you did say his fix didn't make it into the most recent update at the time, so I was just confirming which version it was implemented in. It might be an issue that I didn't get the correct alpha version installed to confirm it Tuesday. 
Please don't remove the frame either way though as it at least gives a consistent order for us to do callouts. 

    On Thursday, March 14, 2024 at 04:22:21 PM EDT, Adam ***@***.***> wrote:  
 
 


I assumed your updates were tested. It's only reason I even merged them. If you do a PR and it's not tested, please mark it as draft.

I simply don't have any means of doing in there and testing it myself for that boss since it's exclusive to era so I don't see it getting fixed any time soon so I may just go ahead and delete that infoframe if it doesn't work.

**Comment by MysticalOS** [comment]
Looking again, it looks like that fix is indeed not in any release version yet. it's alpha only, so if you didn't test alpha you didn't test their fix. Hope that clarifies that. I'll probably do a new tag soon. everything is sort of held up right now by cata beta and not having access to it cause they are refactoring addon code in a way that requires extra attention for ALL game versions that we have to start restructuring some of modules and toc files.
