### ISSUE TITLE
The `/range X` command doesn't work in instance

### ISSUE THREAD

**Issue by Hadrien-DELAITRE** [DeadlyBossMods/DBM-Classic#786]
Hi everyone, thanks for the amazing work here!

**Describe the bug**
The `/range X` feature doesn't work anymore. I don't really know if it's directly related to DBM. But I guess you are aware of this "bug".

**To Reproduce**
Just try in any instance and it will display a message error (not outdoor).

**Screenshots**
![image](https://github.com/DeadlyBossMods/DBM-Classic/assets/9414051/1f0d50d3-8996-461a-a5d2-f1145c36d793)

**Which version of DeadlyBossMods are you using?**
DBM 1.15.18

**Was it working in a previous version? If yes, which was the last good one?**
It was working 1-2 months ago.

**Comment by MysticalOS** [comment]
Forever, it'll be broken forever. not a long time. Blizzard doesn't want this functionality in game anymore. That's what it comes down to.

**Comment by Hadrien-DELAITRE** [comment]
OK, it was an essential information for us in fights like C'thun or KT :/

Thanks a lot for your job!
