### ISSUE TITLE
what is this error ?

### ISSUE THREAD

**Issue by nzzi** [DeadlyBossMods/DBM-Classic#90]
Message: Error loading Interface\AddOns\DBM-Core\Libs\LibStub\LibStub.lua
Time: Fri Feb 14 11:35:29 2020
Count: 2
Stack: Error loading Interface\AddOns\DBM-Core\Libs\LibStub\LibStub.lua

Locals: <none>

=======

Help me plz, thanks.

**Comment by MysticalOS** [comment]
Maybe an issue with stripping libs out of DBM? disable the nolib option on twitch client if using it. otherwise, no idea.

**Comment by nzzi** [comment]
thanks
