### ISSUE TITLE
BWL: Chromaggus spell school vulnerability

### ISSUE THREAD

**Issue by wallrik** [DeadlyBossMods/DBM-Classic#93]
**Is your feature request related to a problem? Please describe.**
For our first BWL clear, a lot of voice comms were used by mages and warlocks yelling FROST! ARCANE! FIRE! SHADOW! It would be nice if this could be automatically communicated within an addon. I'm not sure if DBM is the correct place for it, or if DBM could just help alert when a new vulnerability needs to be found.

**Describe the solution you'd like**
I'd lean towards just having a DBM alert for when Chromaggus emotes "Chromaggus flinches as its skin shimmers." which seems to happen about every 20-25 second.

If this could be limited to default on for only mages and warlocks would probably be nice.

**Describe alternatives you've considered**
An alternative that I would love to see, but I'm not sure how to execute in a good way, would be to check the actual damage of spells after a vulnerability change. But this option is so damn iffy considering it changes depending on which spell you use and the casters spellpower.

If I look at [my own parses](https://classic.warcraftlogs.com/reports/LCbT4DpH2AZ3Pqwn#fight=34&type=damage-done&source=34&options=2), I'd say any normal hit over 200 damage would be considered a successful vulnerable hit. I was struggling a lot to find the vulnerability as you can tell here. When he was vulnerable to arcane my missiles hit for like 250-650, and my frostbolts for 450-850. All other non-vulnerable casts never went above 200 damage.

**Additional context**
Localization and inspiration can be found over at [BigWigs](https://github.com/BigWigsMods/BigWigs_Classic/blob/e71a476aed83a4d2894478b15e80c049104c0931/BlackwingLair/Chromaggus.lua#L129-L219), but they obviously chose to not use the feature as it's commented out.

**Comment by venuatu** [comment]
It's a good idea, my transcriptor has the below for that

25.53, 21.86, 21.89, 20.59, 24.23, 24.21, 17.11, 21.86, 22.91, 19.4, 24.38, 21.84, 18.16, 21.89
20.5, 24.48, 24.22, 24.24, 21.98, 24.28, 16.94, 23.01, 18.23, 17.11, 21.73, 23.12, 21.85, 24.34

which is average 21.85321, stdev at 2.46
```
"<8715.77 23:23:58> [CHAT_MSG_MONSTER_EMOTE] %s flinches as its skin shimmers.#Chromaggus#####0#0##0#17755#nil#0#false#false#false#false", -- [125820]
```

**Comment by venuatu** [comment]
For the second part, detecting what the vulnerability is, it's possible.
Could just work out averages of each spell, and work out what's doing better as of the last emote.
@MysticalOS would that be within dbm scope, or should that be somewhere else?

**Comment by wallrik** [comment]
So apparently you can see the vulnerability buff if you cast detect magic on them, both trash and Chromaggus, but the spell has a hidden cast so it doesn't show up in the combat log. I tested it today just to confirm before I posted here.

There are already a few different weak auras made for this. I'm not sure it's something DBM should do since it requires detect magic. It's not just a "set and forget" alert. People might wonder why the alert isn't working.

The problem without an addon is that they have the same spell icon and no descriptive text on them, so you need an addon to tell you which one they are.

https://classic.wowhead.com/spell=22277
https://classic.wowhead.com/spell=22278
https://classic.wowhead.com/spell=22279
https://classic.wowhead.com/spell=22280
https://classic.wowhead.com/spell=22281

**Comment by venuatu** [comment]
I'm working on a version of that, I'll add those spells into it.
The main thing slowing me down on this is: only getting a single time to test this per week.
