### ISSUE TITLE
Nefarian ClassCall untranslated 

### ISSUE THREAD

**Issue by nzzi** [DeadlyBossMods/DBM-Classic#96]
Hello, Nefarian ClassCall is now untranslated
Can it be modified?

as-is:

if msg == L.YellDK or msg:find(L.YellDK) and self:AntiSpam(5, "ClassCall") then
		self:SendSync("ClassCall", "DK")

to-be(Ex):

if msg == L.YellDK or msg:find(L.YellDK) and self:AntiSpam(5, "ClassCall") then
		self:SendSync("ClassCall", L.YellDKName)

**Comment by nzzi** [comment]
Thanks!

**Comment by Developaws** [comment]
No problem =]
