### ISSUE TITLE
BWL Nefarian occupation call is not running.

### ISSUE THREAD

**Issue by Eric-LiuGang** [DeadlyBossMods/DBM-Classic#97]
Hi

BWL Nefarian occupation call is not running.
and I found in localization.cn.lua that the BOSS dialogue is different from the BOSS dialogue of the current version。

I don't know this issue exists in en and tw。

**Comment by MysticalOS** [comment]
If you can provide logs of the proper messages for your local, I'll fix it. you can either run the addon transcriptor or at very least run /chatlog during the encounter

**Comment by Eric-LiuGang** [comment]
I found some dialogue in BBS，and I will verify later。

	YellShaman	= "萨满祭司，让我看看你们的图腾到底是干什么用的！",
	YellPaladin	= "圣骑士……听说你们有无数条命。让我看看到底是怎么样的吧。",
	YellDruid	= "德鲁伊和你们愚蠢的变形法术。让我们看看有什么事情会发生吧！",
	YellPriest	= "牧师们！如果你们要继续这么治疗的话，那我们就来玩点有趣的东西吧！",
	YellWarrior	= "战士们，我知道你们应该更凶猛一些！让我们来见识一下吧！",
	YellRogue	= "潜行者？不要躲躲藏藏了，勇敢地面对我吧！",
	YellWarlock	= "术士们，不要随便去尝试那些你们根本不理解的法术。看到后果了吧？",
	YellHunter	= "猎人们，还有你们那些讨厌的玩具枪！",
	YellMage	= "你们也是法师？小心别玩火自焚……",

**Comment by Mini-Dragon** [comment]
中文触发语句已经更新。若有问题请继续留issue
zhCN trigger string updated
